### ISSUE TITLE
medium size restriction

### ISSUE THREAD

**Issue by bitno** [coneda/kor#100]
Dear @moritzschepp,

Is there a way to get around the medium size restriction of 100mb? or to change it?

Many thanks and lots of greetings

**Comment by moritzschepp** [comment]
Hey @bitno, yes that's possible, its a setting that you can control via UI at `administration -> general -> application -> maximum file size for uploads`. Alternatively, you can change it in `config/kor.yml`, have a look at https://github.com/coneda/kor/blob/master/config/kor.defaults.yml for how to change the file.

**Comment by bitno** [comment]
Many many thanks, problem solved.
