### ISSUE TITLE
Re-uploading images

### ISSUE THREAD

**Issue by bitno** [coneda/kor#102]
Dear @moritzschepp,

We've talked about this issue before, but I wanted to raise it here as well. 
Once a medium is created and an image uploaded, it is not possible to change the image/re-upload the image. Is this something that should be this way, or is it a bug?

Many thanks and lots of greetigs,
Leo

**Comment by moritzschepp** [comment]
... hmm I just tried that and there is no problem exchanging the image file. So on the entity view, click the pen for editing and upload a new image. I can't remember our previous conversation about this, is this what you are looking for?

**Comment by bitno** [comment]
Unfortunately this doesn't work. Lots of months ago we discussed this and were assuming, that this was an issue of the version used back then. But I still get the error, once I press save. The issue is happening on our kor8 instance, which is running quite a recent master. Would you know, what could be causing this error?

<img width="684" alt="screen shot 2016-11-04 at 2 37 24 pm" src="https://cloud.githubusercontent.com/assets/15378927/20007370/3cdba034-a29c-11e6-8f18-f36cf5b656da.png">

**Comment by bitno** [comment]
On the same instance I have an issuse with video and audio playback, should this maybe be related.

**Comment by moritzschepp** [comment]
So I used 2.0.0 just now and the problem is not there. Can you trigger it and send me the last 1000 lines from log/production.log via mail?

**Comment by bitno** [comment]
Ok, I'll update to the latest master and check again. My computer can't handle the log because of it's huge >8.8gb size! Is that size normal? Any other way to read out the last 1000 lines?

**Comment by moritzschepp** [comment]
Yes that's a bit excessive :) Normally, you'd use something like `logrotate` so ensure a size cap on logfiles. To extract the last 1000 lines of a file and store id in in `production.latest.log` just do

    tail -n 1000 production.log > production.latest.log

**Comment by bitno** [comment]
Many thanks, please find enclosed the log. I'm just about to start the deploy. Fingers crossed!
[production.latest.txt](https://github.com/coneda/kor/files/571871/production.latest.txt)

**Comment by bitno** [comment]
Unfortunately the v2 didn't solve the issue. No video playback and replacing images still returns an error. Many thanks for looking in to this, please do let me know, if there are any other settings I could check.

**Comment by moritzschepp** [comment]
So the logfile shows on line 507 that there is a permission error while deleting one of the thumbnail versions of the old image. Can you verify that the process under which the application is running has permisssion to modify the file?

In general this is strange because the application should have written those files itself and so it should be the owner. Perhaps you ran an import as root or some other privileged user (always use the application's user for that)?

To correct permissions on the data directory, you can run (as root):

    chown -R <username>. /path/to/kor/data

replacing the username with the application's username.

**Comment by bitno** [comment]
Indeed, most of the recent data is written by root and not kor anymore. How can this happen, as all the data input is done through the interface and not through direct imports?

**Comment by moritzschepp** [comment]
Perhaps the application is running as root? Or perhaps the instance is the result of a copy process that was done by root? Also, perhaps the background-process is running as root (`delayed_job`)?

**Comment by moritzschepp** [comment]
@bitno, could you resolve the problem?

**Comment by bitno** [comment]
@moritzschepp , yes, the image upload was fixed by changing the background process to kor. This was done by stopping it as root, changing user to kor and starting it again. (I'm adding this, should others have the same issues).
But, the videos are still not playing, even though the rights have been changed. Will look into this today with Thomas.

**Comment by moritzschepp** [comment]
ffmpeg or avconv need to be installed (depending on what the system provides)

**Comment by bitno** [comment]
Dear @moritzschepp 
I think I might have found something. The log shows, that the videos is being fetched from 
/var/www/rack/kor/releases/20161104161923/data/media/mp4/000/001/261/document.mp4
but this directory doesn't exist. The video is stored at /var/www/rack/kor/shared/data/media/original/000/001/261/document.mp4
for this particular video: https://conedakor8.ethz.ch/media/1261

Any idea why this is happening? Many thanks in advance, the log is enclosed below.
Regards

I, [2017-01-12T09:44:57.088270 #1918]  INFO -- : Started GET "/media/images/mp4/000/001/261/document.mp4?1478265174" for 10.2.12.125 at 2017-01-12 09:44:57 +0100
I, [2017-01-12T09:44:57.089660 #1918]  INFO -- : Processing by MediaController#show as */*
I, [2017-01-12T09:44:57.089721 #1918]  INFO -- :   Parameters: {"1478265174"=>nil, "style"=>"mp4", "id_part_01"=>"000", "id_part_02"=>"001", "id_part_03"=>"261", "attachment"=>"document", "style_extension"=>"mp4"}
I, [2017-01-12T09:44:57.093847 #1918]  INFO -- : Auth: user 'guest' has been seen
I, [2017-01-12T09:44:57.100674 #1918]  INFO -- : Completed 500 Internal Server Error in 11ms (ActiveRecord: 1.1ms)
F, [2017-01-12T09:44:57.101452 #1918] FATAL -- : 
Errno::ENOENT (No such file or directory @ rb_sysopen - /var/www/rack/kor/releases/20161104161923/data/media/mp4/000/001/261/document.mp4):
  app/models/medium.rb:209:in `read'
  app/models/medium.rb:209:in `custom_style_data'
  app/models/medium.rb:165:in `data'
  app/controllers/media_controller.rb:28:in `show'
  app/controllers/application_controller.rb:257:in `profile'

**Comment by moritzschepp** [comment]
Sorry for the late reply, let me investigate this and see if there is some handling issue with mp4

**Comment by moritzschepp** [comment]
Do you know where the request "GET /media/images/mp4/000/001/261/document.mp4?1478265174" comes from? Do you have an idea what page in the browser triggers it?

**Comment by bitno** [comment]
Dear @moritzschepp 
It is the above mentioned media 1261 and this particular link: https://conedakor8.ethz.ch/media/1261.
As I said, somehow the database is fetching a wrong path, but I wasn't able to find this definition anywhere in the code.
Many thanks and greetings,
Leo

**Comment by moritzschepp** [comment]
Hey @bitno! I just klicked on your link again and the video plays fine on firefox, chromium and ie 11.

**Comment by bitno** [comment]
Indeed, because I created the requested folder and copied the file to the new directory. But by default it does not work, because the db does not create the directory the frontend is requesting. Hope this helps

**Comment by moritzschepp** [comment]
I think what might have happened is that the app didn't have the permissions to write to the directory when the video was originally uploaded. Then you corrected the permissions but probably didn't reprocess that the (already existing) entity. For single entities, I'd do this in the console like this:

    Entity.find(1261).medium.document.reprocess!
    Entity.find(1261).medium.image.reprocess!

How is it for new videos?

**Comment by moritzschepp** [comment]
@bitno, can this be closed?

**Comment by bitno** [comment]
Yes, the problem arose by my mistake of triggering the background process with root and not kor. 

Easy fix with 

> root: chown -R kor /var/www/rack/kor/shared/data/media/...
