### ISSUE TITLE
JSON API: Related entity Collection

### ISSUE THREAD

**Issue by anthon** [coneda/kor#104]
Case:
Two Collections, one Public and one Hidden. Public is visible to everyone, and Hidden only to admins.
Right now, as far as I can see, there's no way to restrict the `&include=related` output by Collection. The Collection isn't visible in the output, either, so there's no way to filter stuff on the client.

Suggestion:
A) Introduce a `related_collection` parameter, or
B) Output the Collection as a standard attribute on returned objects, included related entities.

**Comment by moritzschepp** [comment]
Sorry for the late reaction. Both of your suggestions are good ideas. I'll add this to 2.1.0.

**Comment by moritzschepp** [comment]
B) is done, the `collection_id` is included in all entity results now, so A) remains to be done.

**Comment by moritzschepp** [comment]
Oh misread, actually A isn't necessary anymore.
