### ISSUE TITLE
Adressing relations

### ISSUE THREAD

**Issue by bitno** [coneda/kor#107]
Dear @moritzschepp 
The example script [kor/script/custom.example](https://github.com/coneda/kor/blob/master/script/custom.example) you wrote, addresses the scripted creation of relations. 
How does one add from and to entity types? Meaning what is the exact syntax of those two fields?
And when adding relations between to entities, how can one address the additional properties field?

Many many thanks in advance and kind regards,
Leo

**Comment by moritzschepp** [comment]
The keys expect each an array of kind ids and they can be used like this:

    Relation.create(name: '...', reverse_name: '...', from_kind_ids: [1,2,3], to_kind_ids: [3,4,5])

For creating relationship properties, its just like this:

    Relationship.relate(mona_lisa.id, 'has been created by', leonardo.id, ['on a Sunday', 'not verified'])

This would give the relationship the two properties 'on a Sunday' and 'not verified'

**Comment by bitno** [comment]
Much appreciated @moritzschepp !
