### ISSUE TITLE
rewrite new simple search frontend

### ISSUE THREAD

**Issue by moritzschepp** [coneda/kor#108]
The existing simple search frontend often produces failures in tests because the javascript I had used at the time is a bit of a patch work. I'd like to refactor that. I could reproduce the current functionality exactly, but I could also take the opportunity to change it a bit. I could imagine that:

* instead of using selectors for kind and collections filters, we could use the elasticsearch facets to give the user a clickable filter that adapts to his search terms
* same for the tags, its not so clear now why you should select your search string as a term (specifically when there are no tags found)

Overall, this would also make the interface less confusing as the search field would be the first thing on the page.

Makes sense to you?

**Comment by wuebbena** [comment]
Yes, sounds great! And of course you're right with the statement "this would also make the interface less confusing".
btw: Just a few hours ago I've talked with @bitno about the search and maybe he could comment here too.
