### ISSUE TITLE
relating entities by script issue

### ISSUE THREAD

**Issue by bitno** [coneda/kor#109]
Dear @moritzschepp 

I've encountered a problem when relating entities via script. No matter how I write the script, the database doesn't seem to care.

The scenario is: entity1 has a dataset field with the linking id and the medium that I want to relate it to has a distinct name. The data file holds the linking id as well as the distinct name. 

Please find enclosed the script, the data as well as the log. I've tried changing the order, going from medium to document as well, but no change. 

Many thanks for your help or guidance on how I could do this and lots of greetings,
Leo

[data_20170303.txt](https://github.com/coneda/kor/files/816927/data_20170303.txt)
[script_20170303.txt](https://github.com/coneda/kor/files/816928/script_20170303.txt)
[log_20170303.txt](https://github.com/coneda/kor/files/816929/log_20170303.txt)

**Comment by moritzschepp** [comment]
So you are finding a "Dokument" entity via dataset value "dokument_md_id" and a "Medium" entity via its `distinct_name` (this last part sounds strange since that would typically only be filled in if the normal `name` doesn't provide uniqueness). But in any case, in the logs, it looks like it doesn't find `document_entity`. Can you verify that, for example by adding something like `p document_entity` after the if condition?

**Comment by bitno** [comment]
Dear @moritzschepp, will add the check and report. 
The distinct_name on Medium was used to reference the file name, which is our internal id.
In the meantime I've referenced our dokument_md_id to :id and used that. Worked fine and I was able to relate all entities. So the issues lies in reading entities from the dataset field. But a report is coming your way.
Many thanks

**Comment by moritzschepp** [comment]
Ok let me know. Also, there is the point of how searches for dataset attributes are handled: Since the whole dataset is a serialized column in mysql, those searches are done via elasticsearch and therefore rely on it being synchronized.

**Comment by moritzschepp** [comment]
@bitno can this be closed?

**Comment by wuebbena** [comment]
So, what about this issue?

**Comment by bitno** [comment]
Many thanks!
