### ISSUE TITLE
Button to create entity is missing

### ISSUE THREAD

**Issue by bitno** [coneda/kor#112]
Dear @moritzschepp ,

After deploying the current master to our conedakor4 instance, the button to create new entities went missing. Can you please help? Is there a way how to activate it again?

Many thanks and lots of greetings,
Leo
![screen shot 2017-03-10 at 11 06 02 am](https://cloud.githubusercontent.com/assets/15378927/23791035/ca7da52a-0581-11e7-858a-3469adfdfb6a.png)

**Comment by bitno** [comment]
Credentials were missing. My bad, sorry.

**Comment by moritzschepp** [comment]
... ok no problem. It was good I looked at the code anyways because there was some duplication that I hadn't noticed before.
