### ISSUE TITLE
Editable front page

### ISSUE THREAD

**Issue by wuebbena** [coneda/kor#114]
It would be great if the front page (“Welcome…“) could be edited in a simple way. Take, for example, the possibility to change text at "Text for imprint".

**Comment by moritzschepp** [comment]
Very nice, we could do that when we are tackling #35 and #90.

**Comment by Diederka** [comment]
I also wanted to add the html tag <br/> like this: Willkommen im Maya-Bildarchiv! <br/> Welcome to our Mayan Image Archive! 
I put both english and german in here because of the lack of an english and german site-configuration. But the <br/> is visible.

**Comment by moritzschepp** [comment]
Yes, this makes a lot of sense. Also, if html was possible, we wouldn't need two fields anymore (for title and text)

**Comment by moritzschepp** [comment]
This is now done
