### ISSUE TITLE
Tags becoming invisible

### ISSUE THREAD

**Issue by bitno** [coneda/kor#115]
Dear @moritzschepp 
On our conedakor8 instance, the team is working with tags. The discovered a strange behaviour.
You enter tags, but they are being removed by the system. I've enclosed two screenshots of the same entity, visualizing this problem. https://conedakor8.ethz.ch/blaze#/entities/818
before
![before](https://cloud.githubusercontent.com/assets/15378927/25431441/dfb7f03e-2a80-11e7-980b-c315c21cd17a.png)

after
![after](https://cloud.githubusercontent.com/assets/15378927/25431445/e5d0a164-2a80-11e7-84da-63df4d4feff9.png)

The issue is, that the frontend sourcing this data through the API is receiving different answers. Main difference being the missing commas. Screenshots also enclosed.
before 
![tags mit komma](https://cloud.githubusercontent.com/assets/15378927/25431466/f3988a78-2a80-11e7-920f-c9d91d855a78.png)
after
![bildschirmfoto 2017-04-24 um 10 18 37](https://cloud.githubusercontent.com/assets/15378927/25431471/f816de60-2a80-11e7-8c47-eb1a1d1e597e.png)

What is your take on this?
Many thanks as always and kind regards

**Comment by moritzschepp** [comment]
@bitno is the installation on 2.0.0 or something more recent? If it is more recent, can you give me the exacto commit you are using?

**Comment by bitno** [comment]
It is more recent. I think it might be 2017-03-10 12:10:41. But do let me know how to check and I can let you know precisely.
Thanks

**Comment by moritzschepp** [comment]
... that's what I wanted to know, thanks a lot! I will investigate the problem tomorrow evening.

**Comment by moritzschepp** [comment]
So there was an error leading to tags being shown without comma by the edit form (`/entities/1234/edit`). So three tags `green`, `blue`, `yellow` would show as `green blue yellow`. If that form was saved, a single tag was persisted. I just committed a fix for that.

Other than that, it seems that tagging objects are being encoded within the JSON for the entity view (and probably your frontend). That should not happen anymore since 079b7013cf856ecf28647016d0ecd5f6510d5878. You say your installation is more recent, perhaps we should make sure. If you deploy with the deploy script, there should be a REVISION file within the kor directory on the server. If you just pulled it with git, use this within the kor directory on the server: ` git rev-parse HEAD`. One of them should tell us the exact commit hash.

**Comment by bitno** [comment]
Dear @moritzschepp 
This is the content of the Revision file: d2ca054c924bd1589d6feaf28f9ab6ad097631ae
I checked, this is v2.0.0.
Meaning I'm just about to update to the most current master and then hopefully close this issue. 
Regards,
Leo

**Comment by bitno** [comment]
Dear @moritzschepp 
I was not able to deploy as usual. Has something changed in the process?
That's the result I get:

gta-institut-m-87:kor.git lzorc$ ./deploy.sh conedakor8
Warning: Identity file -p not accessible: No such file or directory.
bash: 22: command not found
127
\e[0;34mkor@conedakor8.ethz.ch\e[0m: \e[1;34mmkdir -p /var/www/rack/kor/releases\e[0m
Warning: Identity file kor@conedakor8.ethz.ch not accessible: No such file or directory.
ssh: Could not resolve hostname bash -c "mkdir -p /var/www/rack/kor/releases": nodename nor servname provided, or not known
\e[0;31mdeployment failed with status code 255\e[0m

**Comment by moritzschepp** [comment]
Unfortunately, you are affected by a refactoring that had to be done to allow configurable SSH keys to be used for deployment. As such, the key has to be set now and I didn't mirror that change within `deploy.config.sh.example`. Please add the line setting the key from that file to your `deploy.config.sh` and try again.

Please also make sure that you always have a backup created before deployments.

**Comment by moritzschepp** [comment]
This is to say: I just pushed a new version of `deploy.config.sh.example` where the line is present ...

**Comment by bitno** [comment]
Many thanks. Just checked and I have an id_dsa in my .ssh folder. Does this imply, that I add 
export SSH_KEY="$HOME/.ssh/id_dsa" ?

Backups are being done according to your proposal, one mysql backup and I also do the excel one.
I use 
cat config/database.yml 
- to get the password, which is required after using command
mysqldump -h 127.0.0.1 -u kor -p kor | gzip -c > MyBackUp_YYYYMMDD.sql.gz

**Comment by moritzschepp** [comment]
For backups, its best to just snapshot the vm if you have the option. While the excel backup is better than nothing, it doesn't include the assets.

Yes, the above setting for the SSH key just reflects the default on many systems anyhow, so it should work for you if the deployments worked before.

**Comment by bitno** [comment]
deployment successful!
Many thanks. I will ask the team of this particular instance to check their tags now. 
Many many thanks!!!

**Comment by moritzschepp** [comment]
No problem, sorry for the fuzz.
