### ISSUE TITLE
Relations not being updated

### ISSUE THREAD

**Issue by bitno** [coneda/kor#116]
Dear @moritzschepp 
Changes in the naming of relationships (1 direction) are not being processed. 
I've changed the naming of one direction of one particular relationship type, but it is not being changed. 
I've tried restarting "delayed_job" as well as "touch restart.txt".
The relations.json request shows the correct naming, as well as the gui itself.
Is there any other way to recalculate them?
Many thanks

wrong json, meaning the relation is shown as "zeigte Werke in" and not "zeigte Werke von"
![wrong json](https://cloud.githubusercontent.com/assets/15378927/25654410/2c83b9c8-2ff1-11e7-9678-7f1cc6928a4a.png)

same but in display
![wrong display](https://cloud.githubusercontent.com/assets/15378927/25654411/2c85f2b0-2ff1-11e7-8204-85f0092ad04a.png)

correct relation
![correct gui](https://cloud.githubusercontent.com/assets/15378927/25654412/2c876302-2ff1-11e7-9f1b-ffcb88f0b083.png)

**Comment by moritzschepp** [comment]
Your thinking is right: when you update a relation, all relationships are updated in the background by delayed_job. Depending on how many relationships there are, this might take a few minutes though. Did you wait a bit before checking?

**Comment by bitno** [comment]
many thanks. I did a stop and start this morning before 9am, since then I updated to 2.1 and now I did it again. I'll be patient for another 30 mins, before I comment again ;-D

**Comment by moritzschepp** [comment]
Actually, I'm wrong. The code actually fixes the directed relationships immediately, see
https://github.com/coneda/kor/blob/master/app/models/relation.rb#L17

Can you try to change the relation again and then back to how you want it?

**Comment by bitno** [comment]
Did that as well, but will do again asap.

**Comment by bitno** [comment]
is immediately correct in the gui as well as relations.json, but no change on entities.

**Comment by bitno** [comment]
when I changed the other direction, then it did change, but to the one in the other direction. So it seems it is sourcing the name of the other direction in both cases, even though the entities from and to are different.

**Comment by moritzschepp** [comment]
Oh I think I see the problem. The relation had name = reverse_name before your change, right? That way, the update mechanism would incorrectly update the directed relationships. I'll have a look at the problem this afternoon.

**Comment by bitno** [comment]
Ok, thanks, but they were never called the same way, meaning name = reverse_name was never given. At least not to my knowledge, but I will ask my colleague, who also worked on the instance. 
I have a solution for the moment. I will delete them and re-import, that should solve the issue. Regards

**Comment by moritzschepp** [comment]
Ok there WAS the problem I was referring to before. But perhaps this is not what you are seeing. Can you try renaming the relation once more (you have to make a change otherwise the update mechanism doesn't kick in. So you might have to do two updates) with the new code?

**Comment by bitno** [comment]
I've deleted the relation, created it again and re-imported the links. This workaround solved the issue. 
As my colleague is demoing her work (the instance) later today, I will refrain from doing any changes today. 
But I promise to deploy the latest commit on Friday (as I won't be in the office tomorrow) and try to change one particular direction. Is this acceptable from your end? Shall I leave the issue open until then? Many many thanks, a pleasure as always.

**Comment by moritzschepp** [comment]
Sure, absolutely. Let me know.

**Comment by bitno** [comment]
All perfect, many thanks.
