### ISSUE TITLE
bundler: failed to load command: bin/kor (bin/kor)

### ISSUE THREAD

**Issue by bitno** [coneda/kor#117]
Dear @moritzschepp 
Something I've come across on different instances lately is the following:
Eg. I want to update the index: RAILS_ENV=production bundle exec bin/kor index-all
and I get this particular response:

bundler: failed to load command: bin/kor (bin/kor)
HTTPClient::ReceiveTimeoutError: execution expired
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:792:in `gets'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:792:in `block in parse_header'
  /opt/rbenv/versions/2.2.5/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
  /opt/rbenv/versions/2.2.5/lib/ruby/2.2.0/timeout.rb:98:in `call'
  /opt/rbenv/versions/2.2.5/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:788:in `parse_header'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:771:in `read_header'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:547:in `get_header'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:1294:in `do_get_header'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:1241:in `do_get_block'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:1021:in `block in do_request'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:1129:in `protect_keep_alive_disconnected'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:1016:in `do_request'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:858:in `request'
  /var/www/rack/kor/releases/20170510100050/lib/kor/elastic.rb:391:in `raw_request'
  /var/www/rack/kor/releases/20170510100050/lib/kor/elastic.rb:94:in `index_exists?'
  /var/www/rack/kor/releases/20170510100050/lib/kor/elastic.rb:88:in `drop_index'
  /var/www/rack/kor/releases/20170510100050/lib/kor/tasks.rb:21:in `index_all'
  /var/www/rack/kor/releases/20170510100050/lib/kor/command_line.rb:89:in `task'
  /var/www/rack/kor/releases/20170510100050/lib/kor/command_line.rb:116:in `run'
  bin/kor:11:in `<top (required)>'

Any idea where I might have missed to define this particular command? 
Many thanks

**Comment by moritzschepp** [comment]
Hey @bitno, the further you go "down" in the backtrace, the closer you get to the origin of the problem within ConedaKOR code. It seems like elastic.rb is ultimately triggering it (its the first file that is actually part of ConedaKOR and not of one of its dependencies) The message itself sais that kor's http client didn't get an anwer from elasticsearch ...

Is elasticsearch running and is the configuration in config/database.yml correct?

**Comment by bitno** [comment]
I guess so. How would I check, if the elastic search is running properly?

The settings are as follows:

  elastic:
    host: 127.0.0.1
    port: 9200
    index: kor_production

What do you mean, if these settings are correct?

**Comment by bitno** [comment]
Maybe I need to add, why I was trying to restart the elastic index: The search functionality was not working on this particular instance.

**Comment by moritzschepp** [comment]
The configuration is correct if it reflects your elasticsearch server (in this case it expects it to be running in ip 127.0.0.1, port 9200, which is the default). So to see if some application is listening on that ip/port, netstat can help, e.g. (as root):

    netstat -tlpen

If its not running, then you have to start it. It depends on what platform you are and which init system is in use. Also it depends on how elasticsearch was installed. If you installed it with a debian package, one of the following should work:

    /etc/init.d/elasticsearch start # debian < 8
    service elasticsearch start # ubuntu < 15:04
    systemctl start elasticsearch # debian >= 8, ubuntu >= 15:04

If you installed it manually, that process should reveil how to start/stop the service. BTW, the search within ConedaKOR is not working if the elasticsearch server is down.

**Comment by bitno** [comment]
Many thanks. In the meantime is somehow started working. But taking your code from the last post I received positive answers as well:

> root@conedakor2:/var/www/rack/kor/current# netstat -tlpen
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
> tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      107        11410       1087/mongod     
> tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      109        10513       1259/mysqld     
> tcp        0      0 127.0.0.1:49333         0.0.0.0:*               LISTEN      1001       76808609    12285/current   
> tcp        0      0 129.132.32.172:5525     0.0.0.0:*               LISTEN      0          12797       2060/.tina_daemon.r
> tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          673         1049/sshd       
> tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      0          12314       1329/master     
> tcp6       0      0 :::80                   :::*                    LISTEN      0          11528       1896/apache2    
> tcp6       0      0 127.0.0.1:9200          :::*                    LISTEN      106        885         1177/java       
> tcp6       0      0 127.0.0.1:9300          :::*                    LISTEN      106        11493       1177/java       
> tcp6       0      0 :::22                   :::*                    LISTEN      0          675         1049/sshd       
> tcp6       0      0 :::25                   :::*                    LISTEN      0          12315       1329/master     
> tcp6       0      0 :::443                  :::*                    LISTEN      0          11532       1896/apache2  
> 

and 

> service elasticsearch start # ubuntu < 15:04

resulted in 

> root@conedakor2:/var/www/rack/kor/current# service elasticsearch start # ubuntu < 15:04
>  * Starting Elasticsearch Server                                                                                                                                                                                                                                                * Already running.

So I'll keep this as a reference and thank you very much! Lots of greetings
