### ISSUE TITLE
neo4j guidance

### ISSUE THREAD

**Issue by bitno** [coneda/kor#119]
Dear @moritzschepp 
I promise, this is the last ticket for today. I've been curious about the neo4j export and would need some guidance. 

`RAILS_ENV=production bundle exec bin/kor to-neo --help`
does not provide any further info on that to do

`RAILS_ENV=production bundle exec bin/kor to-neo`
returns the error:

```
bundler: failed to load command: bin/kor (bin/kor)                                                                                                 |Time: 00:00:00| ETA: ??:??:??|
NoMethodError: undefined method `[]' for nil:NilClass
  /var/www/rack/kor/releases/20170510162708/lib/kor/neo_graph.rb:175:in `request'
  /var/www/rack/kor/releases/20170510162708/lib/kor/neo_graph.rb:144:in `cypher'
  /var/www/rack/kor/releases/20170510162708/lib/kor/neo_graph.rb:84:in `store'
  /var/www/rack/kor/releases/20170510162708/lib/kor/neo_graph.rb:67:in `block in import_all'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/batches.rb:124:in `find_in_batches'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/querying.rb:9:in `find_in_batches'
  /var/www/rack/kor/releases/20170510162708/lib/kor/neo_graph.rb:66:in `import_all'
  /var/www/rack/kor/releases/20170510162708/lib/kor/tasks.rb:130:in `to_neo'
  /var/www/rack/kor/releases/20170510162708/lib/kor/command_line.rb:89:in `task'
  /var/www/rack/kor/releases/20170510162708/lib/kor/command_line.rb:132:in `run'
  bin/kor:11:in `<top (required)>'
```
Any guidance on where to enter what settings and how to get this thing going?
Much appreciated

**Comment by bitno** [comment]
in your presentation in January at the Graph conference you mentioned `bin/kor import-erlangen-crm`. Would you be able to tell me, when this command will become public so that I can testdrive it too? Many thanks

**Comment by moritzschepp** [comment]
Its very similar to the connection with elasticsearch, you can find the defaults in
https://github.com/coneda/kor/blob/master/config/database.yml.example

Of course, you will have to set up a neo4j server. With both done, the command should work.

**Comment by bitno** [comment]
Many thanks, that is the thing I was looking for. Will give it another try.

**Comment by moritzschepp** [comment]
The CRM import code is still in another branch. I don't have time now to push that code yet. I'll let you know.
