### ISSUE TITLE
medium upload: is the original filename stored somewhere by default?

### ISSUE THREAD

**Issue by bitno** [coneda/kor#121]
Dear @moritzschepp 
Just a quick question: is the original filename stored somewhere by default? If not, could it potentially be extracted from a log?
Many thanks and lots of greetings

**Comment by moritzschepp** [comment]
Hey @bitno, yes indeed this information is saved with the medium. To retrieve it for a medium-entity id, you can use `Entity.find(12345).medium.image.original_filename`.

**Comment by bitno** [comment]
Many thanks, this just saved our archive...

**Comment by moritzschepp** [comment]
I'm happy to hear that. I guess, I better don't ask what happened ;)

**Comment by bitno** [comment]
Dear @moritzschepp 
Just an additional question: do you have any sample script, on how I could write all original_filenames in one file? Meaning the opposite of the current example script that is part of the code and very useful for importing stuff.

So far I can use your command in the ruby console, but I would need a batch job to return me all kor id's as well as the corresponding original_filename. Ideally this export would include the path as well, on where to find the original in the KOR filesystem: /original/000/001/007 for example.

As always, your help is highly appreciated.

Regards!

**Comment by moritzschepp** [comment]
... no I don't have a script at hand. This is not exactly a daily use case ;) Without the following being tested, it should still give you an idea:

```
Kind.medium_kind.entities.each do |e|
  data = [
    e.id.to_s,
    e.medium.image.original_filename,
    e.medium.path(:original)
  ]
  puts data.join(',')
end
```

This should give you CSV that you may then import in Excel.

**Comment by bitno** [comment]
Worked like a charm. Many many thanks as always. I've included this in my documentation, which we can discuss as some point in the future. In the meantime I might publish bits and pieces of it on my upcoming website, of course with proper credits. Many greetings!
