### ISSUE TITLE
Bug: functionality of configurable help doesn't exist for the english version

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#123]
I created some help texts in german. 
But the functionality of configurable help doesn't exist for the english version. 
Thus the following error warning is displayed, when using help in the english version:  
"translation missing: en.title_verbs.help"

**Comment by moritzschepp** [comment]
Yes indeed, actually the config system is somewhat messy at the moment, please also have a look at #90 and #35. For now, there are no different help texts configurable for each language.

The above message is also shown in German while hovering the help button. This is clearly a bug.

**Comment by moritzschepp** [comment]
This has been resolved in 763c8bab143d4d0414530417fadca7a1cf4f9c36. Adding translatable help is a new feature, see #163
