### ISSUE TITLE
orthography

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#126]
another little spelling error. 
on the administration: 
/relations : 
the heading "relations" is written "realtions"

btw: 
maybe it's because we use an older version of conedakor (we use version 2.0.0-pre). 
but there are some more bugs. i will report them now here. but if thes are fixed in the newer versions, you have to tell me.

**Comment by wuebbena** [comment]
That's still an error in 2.1.0. Thank you for the hint!

**Comment by Diederka** [comment]
Another error: in the englisch profile of kor the expert search fields are named german still: "Name / Titel / UUID" instead of "Name / Title / UUID"
