### ISSUE TITLE
media with no links/relations

### ISSUE THREAD

**Issue by bitno** [coneda/kor#128]
Dear @moritzschepp 
Am I right to assume, that all media, that have no links or relations pointing at them, will be shown under isolated entities? 
Or to rephrase, how would one easily identify media with no relations pointing at them?
We would like to delete all those, as they are not needed.
Many thanks as always

**Comment by wuebbena** [comment]
Yes, but not only media (e.g. persons).
And we are using it in Frankfurt for exactly the case you're mentioning here.

**Comment by bitno** [comment]
@wuebbena many thanks. And how is your process in FFM? Do you delete them one by one or generate some sort of list?

**Comment by wuebbena** [comment]
@bitno One by one. But in our case that's not a problem because there are just the entities which were overlooked (or "lost") in the process of the manual input. So you can easily do it once per week.

**Comment by bitno** [comment]
Many thanks, I just wanted to double check. One of our instances, kor8, is just starting this process.
