### ISSUE TITLE
OAI PMH repo for relations

### ISSUE THREAD

**Issue by S-Peter** [coneda/kor#13]
currently information concerning relations can only be derived via instance data represented by relationships; it would be nice to be able to request relations directly, so that one could deal more easily with changes at the graph's schema level

**Comment by moritzschepp** [comment]
A first version is ready, I also put it in the docs. Be aware that I had to change the oai_dc:dc element to oaidc:dc since oai_dc is actually not a valid namespace name (!)

**Comment by moritzschepp** [comment]
I had misunderstood the specs so I could change the element name back to oai_dc.

Also, the issue can be closed.
