### ISSUE TITLE
CIDOC-CRM branch

### ISSUE THREAD

**Issue by bitno** [coneda/kor#131]
Dear @moritzschepp 
Here I am again, a few questions will follow in the next few days. I'm going to kick things off with the CIDOC-CRM version of KOR. Would you be able to share that branch? Is it far away from the current master?
Many thanks and kind regards,
Leo
PS: Let's skype soon!

**Comment by moritzschepp** [comment]
Hey @bitno ... as a matter of fact, I pushed it this morning, have a look:
https://github.com/coneda/kor/tree/nested_kinds

Yes, indeed, let's skype ;)

**Comment by bitno** [comment]
Great stuff. Just one question of precaution, before I go ahead. In gitk this branch is not linked, like the other two are. Can I still add `export COMMIT="remotes/origin/nested_kinds"` into deploy.config.sh? Or does this mean, that I haven's successfully pulled these "remote" branches? I've included a screenshot of gitk as well as one of the branches. Many thanks and lets talk soon!
![screen shot 2017-10-04 at 4 52 21 pm](https://user-images.githubusercontent.com/15378927/31182708-ed60b98c-a924-11e7-8e77-8ad00d0fffb6.png)
![screen shot 2017-10-04 at 4 55 57 pm](https://user-images.githubusercontent.com/15378927/31182714-f0b0a17e-a924-11e7-9fe0-3a31477977fc.png)

**Comment by moritzschepp** [comment]
The branch list tells us that you fetched the remote branch but you didn't create a local tracking branch for `origin/nested_kinds` yet. Strictly speaking, that's also not necessary but things are easier then. You can do it with

    git branch --track nested_kinds origin/nested_kinds

Then you can use `nested_kinds` with the deploy script. I feel I have to warn you however: This code is in a separate branch because we believe that it requires more testing before we can accept it into the master branch, so make sure you have backups before you deploy it! That said, we are very grateful for all feedback on the new code!

**Comment by bitno** [comment]
Thanks a lot, seems to have worked just fine. 

I'm currently updating kor5 with new data, that's why I might have further questions during the next few days, as data will go in and out all the time. I will update to this new branch and test the CIDOC-CRM functionality, as we have the particular model for kor5 in place. Beforehand I will have to adapt the current KOR model a bit, but promise to provide feedback asap. Again many thanks!
<img width="477" alt="screen shot 2017-10-04 at 6 06 31 pm" src="https://user-images.githubusercontent.com/15378927/31186507-1e8df358-a92f-11e7-95bb-becbcde1ab7f.png">

**Comment by moritzschepp** [comment]
Ok very good. You can also pull a mysql dump on your workstation or virtual machine and try the upgrade there first. The tricky part is always migrating the database when an update brings schema changes. This time there were quite a few e.g. because of #94.
