### ISSUE TITLE
Importing new data

### ISSUE THREAD

**Issue by bitno** [coneda/kor#132]
Dear @moritzschepp 
I hope you can refresh my memory. Can the [Excel Import/Export](https://github.com/coneda/kor#excel-import-and-export) feature be used to import new data? 
If so, which fields are mandatory? Are **name**, **collection_id**, **collection**, **entity_id**, **entity** enough?
Many thanks

**Comment by moritzschepp** [comment]
Yes you can import new data. In that case, fill in at least kind_id, collection_id and name (or no_name_statement).

To be clear: you have to always include all columns but leave the ones blank that you don't need.

**Comment by bitno** [comment]
Ok, I tried that but it didn't work even though I added the new data underneath the old data.
Two follow up questions:
Might it be a problem, that I'm doing this as kor and not root? 
And would it be possible to import a clean sheet, meaning leaving the headers but removing that old data and just adding the new?
Many thanks

**Comment by moritzschepp** [comment]
Yes you should be able to just use an empty sheet, no need to re-import the existing entries. You say that it doesn't work ... is there an error message?

**Comment by bitno** [comment]
Give me a minute, will redo the import with a clean sheet now and check the log.

**Comment by bitno** [comment]
![screen shot 2017-10-06 at 11 46 38 am](https://user-images.githubusercontent.com/15378927/31272658-084845a4-aa8c-11e7-9495-21bb472b0ab4.png)

This is the error I got. 

Sheet looks like this:
![screen shot 2017-10-06 at 11 47 46 am](https://user-images.githubusercontent.com/15378927/31272704-3121d396-aa8c-11e7-8f97-d3383e311c49.png)

**Comment by moritzschepp** [comment]
Sorry, my instructions were incomplete: For the serialized columns, please use their "natural" empty value if you don't use them. So

* for dataset `{}`
* for properties `{}`
* for synonyms: `[]`
* for datings: `[]`

**Comment by bitno** [comment]
worked like a charm ;-D

**Comment by moritzschepp** [comment]
The docs are updated accordingly, have  a look at the readme.

**Comment by bitno** [comment]
Very good: https://github.com/coneda/kor/blob/master/README.md#excel-import-and-export
