### ISSUE TITLE
searching distinct name in the KOR frontend

### ISSUE THREAD

**Issue by bitno** [coneda/kor#134]
Dear @moritzschepp 

Would it be possible to enable the search to look for the distinct_name as well?
I guess the simple search might even include that field, but I would need a way to filter by this particular field, ideally through the expert search and making this field visible there. 

Much appreciated, Leo

**Comment by moritzschepp** [comment]
Yes, the simple search includes `name` and `distinct_name` but as separate values. I'll keep this ticket as a feature request.

May I ask what your use case is?

**Comment by bitno** [comment]
Sure. In our db's the name might not be unique, that's why we use the distinct name to add a unique name to the entry. In most cases it's a signature or id. A lot of editing work relies in finding the entry with a clear search term, in this case the signature. Just searching for that signature in the simple search returns lots of results.

Eg. https://conedakor5.ethz.ch/
Signature is: uzh-khist-gd-04207-53
Search in simple search returns 934 results

A workaround is using quotation marks "uzh-khist-gd-04207-53", but ideally we would search the term in the correct field in the expert search.

**Comment by moritzschepp** [comment]
I understand, thanks for the clarification.

**Comment by moritzschepp** [comment]
This works already in v4: KOR doesn't try to alter the search terms anymore (which is probably why the search term `uzh-khist-gd-04207-53` got broken up into singular, or-connected terms, leading to many results).
