### ISSUE TITLE
searching media through the KOR frontend

### ISSUE THREAD

**Issue by bitno** [coneda/kor#135]
Dear @moritzschepp 

Another search question: Would it be possible to add the entity type **media** to the search? Especially expert search.

Much appreciated as well and kind regards,
Leo

**Comment by wuebbena** [comment]
Hello @bitno, could you specify the question? What do you want to search exactly? Some technical facts like the file size?

**Comment by bitno** [comment]
@wuebbena sure. For example **id**, **distinct_name**, any user generated **fields**. This is all information currently stored and visible for the user in the frontend. 

Ideally, if somehow possible, a search over **image_file_name**, **image_content_type**, **image_file_size** would be a bonus, with a focus on **image_file_name**.

Hope this helps, otherwise please do let me know.

Many many thanks as always ;D

![screen shot 2017-10-06 at 9 29 50 am](https://user-images.githubusercontent.com/15378927/31267715-7070bba6-aa79-11e7-831e-fbdf04d36cb2.png)
![screen shot 2017-10-06 at 9 32 21 am](https://user-images.githubusercontent.com/15378927/31267716-70753a28-aa79-11e7-9d65-f26b2bbcf442.png)

**Comment by moritzschepp** [comment]
Yes this is a very good idea.

There shouldn't be a name nor distinct name for a Medium though. Unfortunately, there was a version of KOR that allowed setting those fields but later this was fixed.

**Comment by wuebbena** [comment]
@bitno I see, thanks for the explanation.

**Comment by bitno** [comment]
Ok, how will you proceed with this question? I can live without the name and would move distinct_name into a new field.

**Comment by moritzschepp** [comment]
That seems to be a good solution. We could fail the migrations to the next version if any medium has a name / distinct_name. What do you think?

**Comment by bitno** [comment]
I think removing distinct_name would be a problem, as a few of our instances have that field. 
But if you decide to do that, please let me know ahead, so that I can move that information to a new field.

**Comment by moritzschepp** [comment]
Hmm ok so since that was considered a bug, we just fixed it (April 2016), see 861ad4215ec7e16b3e87cf850c361a2b14aa6797. It therefore also went into v2.0.0. Can you migrate your data before you upgrade to that version?

**Comment by bitno** [comment]
Many many thanks, this information is really important. KOR5 is one of our last 2pre instances, and I will take care of this before I deploy the current master. Again many thanks for making me aware, because I was planning on upgrading this weekend.

**Comment by Diederka** [comment]
We also use distinct_name of media for relating our media to the other entities . 
so it would be bad for us to remove them. 

But I also agree with bitno. I think it would be helpful to search for the original filenames of archival records (which often are the file names of the images (the medium))
in our case the name of the archival record = the filename as well as  = a dataset property named image_number. so either to search for a dataset property or for the distinct name of the medium would be great.

**Comment by Diederka** [comment]
Sorry, I take my question back. :-) The identifiers can be resolved and be found ... As you wrote  
"In KOR, identifiers can be "resolved" with /resolve/<field>/<identifier>. That's is excellent. And it will be good enough for searching.

**Comment by moritzschepp** [comment]
The actual feature was implemented with v4.0.0. Please open another issue if your data can't be migrated easily.
