### ISSUE TITLE
ruby script import csv question split()

### ISSUE THREAD

**Issue by bitno** [coneda/kor#136]
Dear @moritzschepp 

How can I get rid of csv conventions when using scripts to import data?
Example, take this data:

```
Unique_ID;Data
uzh-khist-gd-04209-02;"Universität; Glasdiasammlung des Kunsthistorischen Institutes, Inv.-Nr. 4209-02"
```
two columns, separated with semicolon ; and data separated with quotation marks "
I need the data separation, because a semicolon ; might be part of the string as well, as documented in the example.

Is there a way, how one could import the string into KOR without quotation marks ""?

Many many thanks
Leo

**Comment by bitno** [comment]
Found a way myself.

Just added this snipped after the bracket

before
`fields[1]
`
after
`fields[1].tr_s('"', '').strip
`
result: happiness

**Comment by bitno** [comment]
the strip is removing all quotation marks.
Would you know a better way? Or is in this case the the split() function not the right way to do it? Would something like parse be better suited?

**Comment by moritzschepp** [comment]
The easiest way to do those things I found in the past, is to use a different separator when generating the CSV and not use quotes unless they are part of the actual data. If you can't control the CSV generation process, then you could use a regex to just remove quotes at the beginning or the end of the values. In python you would:

``` python
# load the regex module
import re
...
fields[1] = re.sub('(^"|"$)', '', fields[1])
...
```

**Comment by bitno** [comment]
ok, I'll try a tab separated csv and will report back

**Comment by moritzschepp** [comment]
I found that using a pipe (`|`) works in many cases.

**Comment by bitno** [comment]
I will use `|` in this case, the test worked just fine. But Foto Marburg is using this in their Bildindex URLs to make anchors. http://www.bildindex.de/dokumente/html/obj20830578#|home 
So I will keep an eye open on a better solution going forward. Many thanks

**Comment by moritzschepp** [comment]
You can also use `||` ;)
