### ISSUE TITLE
dataset array not consistent

### ISSUE THREAD

**Issue by bitno** [coneda/kor#137]
Dear @moritzschepp 

Something that I noticed when trying to sort the JSON array of the dataset column through a python script. 
The array is not consistent. In most cases, all keys and their values are written in there, but not in all. Some show only a selection of keys and values others are empty and show no data at all.

I'm of course talking about the same entity type here.

Is there a way how to trigger a recalc, or should this be this way? I tried delayed_job already.

Many thanks
Leo
![screen shot 2017-10-06 at 11 04 46 am](https://user-images.githubusercontent.com/15378927/31270968-adf36368-aa86-11e7-9795-86ad8ea24cc0.png)
![screen shot 2017-10-06 at 11 04 29 am](https://user-images.githubusercontent.com/15378927/31270967-adf200c2-aa86-11e7-804e-ea411ec350b8.png)

**Comment by bitno** [comment]
I already indicated, why I'm asking this. I need all the keys which have a value in them, not null. And I want those keys as column headers and their respective values in this particular column.
The script I'm using is sorting the JSON first, that's why I can't use the current db export.

See code here
```
#Script to transpose and sort fields in the KOR JSON
#field should become a column header, the values shall all be placed in that newly created column.
#how can I check, if there are any properties or synonyms in all of them.

import csv
import json

header_written = False

with open("transpose.csv", "w") as fh_out:
    writer = csv.writer(fh_out, delimiter=",")
    with open("Start_Array.csv", "r") as fh:
         reader = csv.reader(fh, delimiter=",")
         print(reader.next())
         for row in reader:
             
             id = row[0]
             jsoncell = json.loads(row[1].decode("utf-8"))
             print(jsoncell)
             if "fields" not in jsoncell:
                 continue
             fields = jsoncell["fields"]
             
             if not header_written:
                 header_written = True
                 writer.writerow(["id"] + sorted(fields.keys()) + ["synonyms"])
             
             new_row = [id]
             for entry in sorted(fields.keys()):
                 new_row.append(fields[entry].encode("utf-8"))
             
             if "synonyms" in jsoncell:
                 cell = ", ".join(jsoncell["synonyms"])
                 new_row.append(cell.encode("utf-8"))
                 # new_row.extend(jsoncell["properties"])
                 # new_row.extend(jsoncell["synonyms"])
             
             writer.writerow(new_row)
             

```

**Comment by moritzschepp** [comment]
I'm not sure I understand, but the dataset only get's written if there is meaningful data. So if you create a field `dokument_datierung_display` for a kind `Dokument` then none of the existing entities will have any value for that new field. If that is the only field you have, the excel output would be `{}`. However, I don't see a way how that could be a problem?

If you instead need a hash à la `{'dokument_datierung_display': null}` then it would be easy to extend the python script to add the missing keys ... e.g. after `jsoncell = json.loads(row[1].decode("utf-8"))`

**Comment by bitno** [comment]
Ok, understood. I falsely got the impression that the JSON array included all fields, no matter when they were added and if the keys have any values. But as I understand now, this is not the case.

I will change my python script accordingly. As soon as it works well, it is going to github, so that other KOR users can use it.

Thanks

**Comment by moritzschepp** [comment]
Thanks to you! I'm eager to see your code!

**Comment by bitno** [comment]
This will take some time, as I'm really busy getting kor5 started again. 
But I will have to iterate through each line as well as the header, my current code will not work on different json arrays. This is going to require some thinking over the weekend. And for full disclosure, the Code Clinic and especially Uwe have been of great help in the past, as I'm a complete python newbie. ;D
