### ISSUE TITLE
change edit relation color

### ISSUE THREAD

**Issue by bitno** [coneda/kor#139]
Dear @moritzschepp 
I haven't found the information, where the color of the edit area of the relation (relationship_editor_visible) is stored and where it could be changed. Could you please help?
Many thanks and kind regards

![bildschirmfoto 2017-10-30 um 13 11 09](https://user-images.githubusercontent.com/15378927/32170303-4cfd61d4-bd74-11e7-9abd-64050f9fe2e8.png)

**Comment by moritzschepp** [comment]
The principal component here is the `kor-relationship-editor` and it is styled here:
https://github.com/coneda/kor/blob/master/app/assets/stylesheets/modules/widgets.css.sass#L14

I know, not very obvious ...

You might have to recompile the assets, depending on your setup.

**Comment by bitno** [comment]
Ok, many thanks. I was on the right track with widget.css.sass. How do I recompile correctly? I tried `touch restart.txt` , but it didn't solve it.

**Comment by bitno** [comment]
`RAILS_ENV=production bundle exec rake assets:precompile`

reading helps

**Comment by bitno** [comment]
The color change worked just fine.

**Comment by moritzschepp** [comment]
Yes exactly, its one of the deployment tasks
