### ISSUE TITLE
BUG: No uploaded Images are displayed in browser

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#141]
It doesn't matter, if images get uploaded per multiupload or separated. 
It also doesn't matter, if Tiffs or Jpgs are uploaded. 
Wheter we klick on "enlarge", or "maximize". Neither image is shown after upload. 
Only after klicking on "original" , the image is shown in a new window. 
Downoading of the image is also possivle. 
But a display of media is not given. 
Example: 
https://classicmayan.kor.de.dariah.eu/blaze#/entities/991

**Comment by wuebbena** [comment]
Hm, looks like a problem with the permissions. The user is part of a group which is allowed to display the images and not just „Download originals“?

**Comment by moritzschepp** [comment]
Or perhaps the background process to generate the various versions is just not running. Have a look at the last few paragraphs of https://github.com/coneda/kor#scripted-installation for how this process can be managed.

**Comment by Diederka** [comment]
Still the Problem is there: All images have been uploaded per multiupload via browser. And the rights to be displayed are set (viewable by guests without login) there but still no medium is displayed yet. 
Not even the random selected images on the start screen are displayable, though no login is necessary to see them. See: https://classicmayan.kor.de.dariah.eu/

**Comment by moritzschepp** [comment]
The background process is either not processing the images or the app is not delivering them. It depends on the setup and on the error messages (if any) that are given. Did you contact DARIAH support about this?

**Comment by Diederka** [comment]
No, I didn't yet. So further software Problems are not to be commited via github?

**Comment by wuebbena** [comment]
GitHub is still the right platform when it comes to the code. In this case an issue in the actual installation is probably the problem, not the code. Therefore, only the admin with the appropriate rights on https://classicmayan.kor.de.dariah.eu/ can help here to locate the error.

**Comment by Diederka** [comment]
OK. Thank you!
