### ISSUE TITLE
local ids of kinds not exported via oaipmh

### ISSUE THREAD

**Issue by S-Peter** [coneda/kor#15]
in order to map the local from and to ids of relations, the local id of kinds is necessary. These are not exported via oaipmh's ListRecords

**Comment by moritzschepp** [comment]
.. right. However, I'd prefer to keep it consistent with the entities API. I just changed the relations XML to look like

    <kor:from-types>
      <kor:type kor:id="ce6afaea-d8b6-4d79-b481-f28dcc15a16a">Person</kor:type>
    </kor:from-types>
    <kor:to-types>
      <kor:type kor:id="ce6afaea-d8b6-4d79-b481-f28dcc15a16a">Person</kor:type>
    </kor:to-types>

does that also work for you?

**Comment by S-Peter** [comment]
that's even better
