### ISSUE TITLE
How can I delete Testdata (entities and relationships)? 

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#151]
In the given custom.example I only find how delete all kinds, entities, relations and relationships.  

"# destroy all kinds, entities, relations and relationships except the Medium kind
	  Kind.without_media.each{|r| r.really_destroy!}
	  Relation.all.each{|r| r.really_destroy!}"

But I want do delete only the entities and relationships I built in the database to clear everything and start to ingest new data. 
I want to keep my given kinds and relations

How can this be accomplished?

**Comment by moritzschepp** [comment]
It can be done as follows:

    Entity.find_each{|e| e.really_destroy!}

Since destroying an entity entails the deletion of all its relationships, the above removes all relationships as well.

**Comment by Diederka** [comment]
Thanks! That helped!
