### ISSUE TITLE
What characters are not allowed in the initial import_file?

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#152]
I still have problems with the initial import-file (excel oder csv). I use a semicolon-separated csv.  
I have ruby scripts for every entity and I let them run, so they can pick the according content from the source-csv.  so far so good. 
The import does not schow any errors this way... but when I look into the database, 
I realise there are many many errors in the datafields. 
Some fields are filled correctly, some are not filled at all and some with the wrong content. 
I reckon it has to do with content in the source file, which can not be parsed ... ? 
So my question, which characters are not allowed in the sorurce-csv. (apart from whitespace and ;) ? 

See source_example file and ruby-script for artefact (here txt): 
[import_Artefact.txt](https://github.com/coneda/kor/files/1635736/import_Artefact.txt)
[source-example.txt](https://github.com/coneda/kor/files/1635739/source-example.txt)

**Comment by Diederka** [comment]
[source-example.txt](https://github.com/coneda/kor/files/1635728/source-example.txt)
[import_Artefact.txt](https://github.com/coneda/kor/files/1635733/import_Artefact.txt)

**Comment by moritzschepp** [comment]
There is nothing generally blocked within CSV files. I'd make sure that they are always UTF-8 encoded so that there are no conversion problems.

The matching between CSV columns and kor fields is up to the script and depends on the defined fields for the respective entity type. Can you not change the `jsonData` structure to match your needs? E.g. your CSV seems to include 23 fields per line but the last one you are using to build `jsonData` is only the 17th?

**Comment by Diederka** [comment]
I have separated scripts for every entity. 
The script for the Site e.g. will use the field in column 23. 
But should I rather create a Script for all entities, so that all columns get used to build the data? 
I didn't think my kind of separation could be a source for errors.

**Comment by moritzschepp** [comment]
With one script for every entity, do you mean for every entity type? If so, then if you can determine from a CSV row what type of entity it should lead to, then write one script if not, write several but then you'd have to split the CSV file into several files ... on for each entity type.

One potential problem with `site.txt` I can see is that you are creating entities with type `document` which in turn is set to `Medium`. However, you are not adding any image data.

**Comment by moritzschepp** [comment]
Is this problem solved for you?

**Comment by Diederka** [comment]
Sorry, yes I meant entity type (kind). We have 5 kinds: medium, Person, Archaeological Site, Place, Holder. Oh ok, I see. I didn't want to split the source-csv into 5. But okay, I will have to chose one of the two possible ways. Thanks!
