### ISSUE TITLE
how to fill the dating information fieldautomatically at import?

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#153]
We have managed so far the initial imports per one excel-table by creating the JSON Strings for the dataset-input. (https://github.com/coneda/kor/issues/152). 
But there is one field, which we cannot import by reading it out from our excel and filling it. 
It is not in the dataset but has an own field in the export excel in column "q" for datings:  
It's our dating information with the chosen value year. If I manually fill in the dating information in the browser input form for an uploaded medium I would e.g. give in a type of dating: "year" and the dating will be filled: "1978". In the export file a String with our dating field would look like this:  [{"id":1,"label":"Year","dating_string":"1982"}] 
But how can we import it by means of a rubyskript? Creating a JSON String didn't work here so far.

**Comment by moritzschepp** [comment]
In ruby, you can create an entity with dating information like this:

    Entity.create(
      ...
      title: "some title",
      datings: [
        EntityDating.new(dating_string: '1982'),
        EntityDating.new(dating_string: '1999'),
        ...
      ]
      ...
    )

Let me know if this doesn't help.

**Comment by Diederka** [comment]
It didn't work.

**Comment by Sentient6** [comment]
Dear Moritz,

thanks for the tip. But we got the error that dating is invalid.
We make that:

Entity.new(
  :kind => document,
  :collection => default,
  :dataset => jsonData,
  :datings => [
               	EntityDating.new(dating_string: fields[16])
              ]
  )

In fields[16] just stand year like 1968 and so on.
Even if I write a specific value (EntityDating.new(dating_string: '1986')) into the brackets I got the same error. 

One example Output by trying to import:

`_id: nil, subtype: nil, medium_id: nil, attachment: {"fields"=>"{\"picture_no\" : \"KHM_1999_F561_R07_35\", \"folder_no\" : \"9\", \"image_description\" : \"Edzna, Stela 24, Fragment\"}", "properties"=>[]}, deleted_at: nil>
["Datings label has to be filled in", "Datings is invalid", "Medium Without a relevant file the entity cannot be created as a medium"]`

Can you hel me regarding this issue?

The missing of a relevant file is another problem. But I think we should talk about that in another ticket.

**Comment by moritzschepp** [comment]
Yes, sorry I forgot the label part. So a dating for an entity consists of two parts: a label (e.g. "date of birth") and the actual date value (e.g. "1968"). So the objects have to be created like this:

    EntityDating.new(label: "date of birth", dating_string: "1968")

That should get rid of the label problem. The missing file error pops up because you chose Kind "Medium" for the entity type. That type is reserved for media uploads and therefore entities of that type require a file, as in:

    Entity.new(
      ..
      medium: Medium.new(document: File.open("/path/to/file"))
      ..
    )

Let me know if this doesn't work out.

BTW, {some: "thing"} is ruby's new hash notation. Before, this would have been written as {:some => "thing"}. Both are valid.

**Comment by Sentient6** [comment]
Thanks alot that solved the problem regarding the datings. 

And also thanks for the tip of the new hash notation. It is better readable.

**Comment by moritzschepp** [comment]
Ok very good :) Can this issue be closed?

**Comment by MaximilianBrodhun** [comment]
Yes, this issue can be cloed :)
