### ISSUE TITLE
How to give a medium a relevant file?

### ISSUE THREAD

**Issue by MaximilianBrodhun** [coneda/kor#154]
By the attempt of imorting a medium file I got the error
`["Medium Without a relevant file the entity cannot be created as a medium"]`

I thought that the relevant file is given by the filename of the upload image. 
Inside the "dataset " we habe this information with the key "picture_no" and in the source file it is field[1].

Should I write this inside the another field of the entity Creation?

The code is the following:

```
KOR_ROOT="/home/kor/kor/"

# loading the rails environment
require "#{KOR_ROOT}/config/environment"
require 'json'
default = Collection.where(:name => 'Guest Collection').first
document = Kind.where(:name => 'medium').first

File.read("/home/kor/sourceFiles/source_import_16.01.csv").split("\n")[1..-1].each do |line|

 fields = line.split(";")

  jsonData = "{\"picture_no\" : \"" + fields[1] + "\", \"folder_no\" : \"" + fields[0] + "\", \"image_description\" : \"" + fields[12] + "\"}"
  jsonObj = JSON.parse(jsonData)

  work = Entity.new(
  :kind => document,
  :collection => default,
  :dataset => jsonData,
  :datings => [
               	EntityDating.new(label: "year", dating_string: fields[16])
              ]
  )

  if work.valid?
    p work
    work.save
  else
    p work
    p work.errors.full_messages
  end
end
```

**Comment by moritzschepp** [comment]
Yes, it has to go to another field. The reason is that kor is processing images (creating thumbnails, extracting stats etc.) when they are added to the system. You have to create an entity (of type "medium") like this:

    work = Entity.new(
      kind: document, # since this is set to the medium type above
      medium: Medium.new(document: File.open("/path/to/file")), # perhaps in your case, this is File.open(fields[1])?
      ... your other attributes as before ...
    )

This will import the original into the system. To actually process the image, the background task has to be run. On dev servers, this can be accomplished with

    bundle exec rake jobs:work

Additionally, if you run a dev server, images will only show if SHOW_MEDIA is true, so just run

    SHOW_MEDIA=true bundle exec rails s

**Comment by MaximilianBrodhun** [comment]
Great, the problem is solved and the issue can be cloed.

Thanks a lot

**Comment by moritzschepp** [comment]
No problem, I'm glad it works!
