### ISSUE TITLE
code maintenance (summary)

### ISSUE THREAD

**Issue by moritzschepp** [coneda/kor#155]
* make travis ci work again
* complete JSON API
* complete Frontend on RiotJS (consider #108)
* sucker punch instead of delayed job & usablity (consider #40, #36)
* upgrade rails and other gem dependencies
* rethink error handling (consider #37, #156 )
* rethink configuration system (consider #35)
* rethink deployment options (make it a ruby gem?) (consider #26, #90, #123)
* rethink session management (consider #39)
* refactor test suit (unify fixtures & setup code, transform relevant integration tests to unit tests)
* rethink audit log (currently only exists for auth in in form of production.log)

**Comment by moritzschepp** [comment]
@wuebbena I think we have taken care of all aspects here, except the audit log (which we should make a ticket for once the requirement arises). What do you think?

**Comment by wuebbena** [comment]
Yes, I'm with you on that.
