### ISSUE TITLE
How to create relations between entities?

### ISSUE THREAD

**Issue by MaximilianBrodhun** [coneda/kor#157]
I want to create a relation between an metadata file and an image. It seems it doesn't work since no relation is visible in the web interface. But I don't get back any error messages.

My attempt looks like this:

```

KOR_ROOT="/home/kor/kor/"
require "#{KOR_ROOT}/config/environment"

 
default = Collection.where(:name => 'default').first
medium = Kind.where(:name => 'Medium').first
artefact = Kind.where(:name => 'Artefact').first

medium.entities.each do |medium_entity|
  artefact.entities.where(:distinct_name => medium_entity.distinct_name).each do |artefact_entity|
    Relationship.relate_and_save(medium_entity, "depicts artefact", artefact_entity)
  end
end

```

**Comment by moritzschepp** [comment]
It depends a bit on the version you are using. But in any case, with activerecord objects, you can always do this:

    my_relationship = Relationship.relate_and_save(...)
    unless my_relationship.valid?
      p my_relationship.errors
      exit # that exits the whole process
    end

That should give you an idea of why the relationship wasn't saved. If it was, perhaps you are having a permissions problem?

**Comment by MaximilianBrodhun** [comment]
Tanks for this!

May be my understanding wasn't correct. With the line

`artefact.entities.where(:distinct_name => medium_entity.distinct_name).each do`

I choose the entities which should put into relation. That is similiar to a join from SQL (?). So the distinct name of the artefact entity (in my case) have to be the same as the content of "medium_entity.distinct_name".

Is that correct?

**Comment by moritzschepp** [comment]
I'm not 100% sure if I understand what you want to do but your query basically is a 

    SELECT * FROM entities
    WHERE 
      kind_id = <artefact.id> AND 
      distinct_name = <medium_entity.distinct_name>

There is no JOIN happening as far as I know. You can always do this:

    puts artefact.entities.where(:distinct_name => medium_entity.distinct_name).to_sql

that spits out the SQL query generated by that sequence. BTW, this api is not written by ourselves, it is part of the ActiveRecord library which has excellent documentation in form of the ruby on rails guides. Perhaps you find that useful: http://guides.rubyonrails.org/v4.2/active_record_querying.html

**Comment by MaximilianBrodhun** [comment]
I solved the problem. 

The problem was based on our data.

**Comment by moritzschepp** [comment]
I'm happy you could resolve it.
