### ISSUE TITLE
problem in frontend. editing of entity types fields not possible

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#158]
I have this problem for weeks now. I tried different browsers. neither gave me the opportunity to edit one specific kind in our database. All the others of the 6 kinds are ok and editable by browser. 
But the fields of the kind with the id 2 are not editable here. 
See: 
https://classicmayan.kor.de.dariah.eu/kinds/2/fields

**Comment by moritzschepp** [comment]
Can you provide more details? What is the exact problem? The button for to the field editor doesn't show? The form doesn't show or when you submit it, there is an error?

**Comment by Diederka** [comment]
watch this screenshot. you see, the problem seems to be graphically corrupt display, which makes it impossible to klick any fields or buttons. https://we.tl/s6I8ng1pMN

**Comment by moritzschepp** [comment]
It seems the field names are so long that they are overflowing the table's layout. That is a bug and I will commit a fix shortly.

A workaround is to simply enter the url of the field form into your browser, so in your case: 
https://classicmayan.kor.de.dariah.eu/kinds/2/fields/<field_id>/edit

If you hover the edit button or delete button on each field, the field id will be shown at the bottom of the page.

**Comment by Diederka** [comment]
Still not possible to delete the field. 
I can edit it, but I want to delete for example field 39. 
is there something possible as workaround like "https://classicmayan.kor.de.dariah.eu/kinds/2/fields/39/delete" ?

**Comment by moritzschepp** [comment]
Good idea, but unfortunately that doesn't work because the HTTP Verb has to be DELETE which can't be simulated with a (simple) url. The only option I see is to modify the css on the page with the field list. You can do this in the developer console of your browser and jquery:

    $('table.kor_table').css('table-layout', 'fixed')
    $('td.expanding').css({width: 150, overflow: 'hidden'})

Of course those changes only persist until you refresh the page but it should let you click the buttons.
