### ISSUE TITLE
is it possible to use another entity type's field in a generator field

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#160]
For the entity types medium I have made a rights-field called "licence" with a generator code: 

<span ng-if="entity.dataset.licence">
This Image is created by {{entity.dataset.licence}} available under the following Creative Commons Licence CC by 4.0. Provided by the Maya Image Archive of Project Text Database and Dictionary of Classic Mayan.
<a href="https://creativecommons.org/licenses/by/4.0">
Click here for more information about the Creative Commons Licence.
</a>

As workaround for now I put the name of the creator in the "rights" field. 
But eventually I'd like to put in there "cc by 4.0" . And after the passage "created by"  I would like to put the name of the person who created the medium. In our database the relation between person and medium is:  created medium, was created by person. 
Is it possible to to use the content of the person's field "person.name" (which is also no dataset field) in the medium's generator field?

**Comment by moritzschepp** [comment]
Your workaround is the only way I can think of for the moment. The generators can only access the current entity's data, not from related ones.

**Comment by Diederka** [comment]
Alright. No Problem. I will add another Generator Field then , ohne for the name, ohne for the licence.
