### ISSUE TITLE
Create Relationship by content of dataset

### ISSUE THREAD

**Issue by MaximilianBrodhun** [coneda/kor#162]
Is there anyway to create a relationship by using the content of the field dataset in json format?
In my tests it just as possible to get the whole content of dataset and not a particular field.

I have the following code

```
relationship = 
  medium.entities.each do |medium_entity|
        artefact.entities.where(:distinct_name => medium_entity.distinct_name).each do |artefact_entity|
      Relationship.relate_and_save(medium_entity, "depicts artefact", artefact_entity)
    end
  end 
```

And I would do something like this:

```
relationship = 
  holder.entities.each do |holder_entity|
        artefact.entities.where(:distinct_name => holder_entity.dataset.idOfHolder).each do |artefact_entity|
      Relationship.relate_and_save(artefact_entity, "is held by holder", holder_entity)
    end
  end 
```

**Comment by MaximilianBrodhun** [comment]
I solved the problem

**Comment by moritzschepp** [comment]
Your code should work. If it doesn't, please post specific error messages or undesired results.

**Comment by MaximilianBrodhun** [comment]
Ok, I just thought I solved the problem.

To explain the problem a little bit more:

We have the two entites artefact and holder. We want to create a relationship between those entities.
It wasn't possible to make the schema in a way that we 


```
relationship =
  holder.entities.each do |holder_entity|
    artefact.entities.where(:attachement['relation_key'] => holder_entity.dataset['relation_key']).each do |artefact_entity|
      Relationship.relate_and_save(holder_entity, "holds artefact", artefact_entity)
    end
```

**Comment by MaximilianBrodhun** [comment]
Everything works! Sorry for the confusing openings and closings.

And thanks for your reply.

**Comment by moritzschepp** [comment]
No problem :)
