### ISSUE TITLE
problem in creating relationships by script (creating double (or triple) entries and building not all relations)

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#165]
since we found out, that relationships can only be built over "name" or "distinct_name" (or comment?) we have made our own workaround in buildig relationships scripts .but we still have problems. for instance  when creating 5 existing holders with 10 places, we have to use the script "place locates holder" instead of" holder is located in place", because otherwise it would only create 5 relations (for 5 holders)  but not vice versa for the 10 places back, and that's it. 
so we assumed, we have always to build from the entities, we have most of. but why does it create the bidirection automatically? 
and why doenst it create all directions vice versa? 
and why does it sometimes create double entries? 
it does so for place and artefacts. and more.  
and why doesnt it build realtions at all sometimes? 
sometimes we use the distinct_name and sometimes the name for our relations:  

first we create the entities (here holders and places) like so from our excel:  
as you can see, we put the relations into the import scripts before to be able to build them afterwards by name /distinct_name: 
https://github.com/Diederka/Maya-Image-Database-TWKM-Scripts_UnderConstruction/tree/Import_Entities
here some script examples: 

After importing all entities, we create the respective relations holder - place like so: 
see example scripts: 
https://github.com/Diederka/Maya-Image-Database-TWKM-Scripts_UnderConstruction/tree/Import-_Relations

**Comment by moritzschepp** [comment]
If I understand correctly, you need a way to see what relationships were created by your scripts and why. The `Relationship#relate_and_save` method creates a single relationship including the reversal. So e.g. 

~~~ ruby
from = Entity.where(name: 'Leonardo').first
to = Entity.where(name: 'Mona Lisa').first
relationship = Relationship.relate_and_save(from, 'has created', to)
~~~

Will create a relationship "Leonardo has created Mona Lisa" and "Mona Lisa has been created by Leonardo" (if the Relation's reverse name is 'has been created by'). This code tries to find a relation with the given name and which allows the types of the given entities. If it found a relation, it will create the relationship and return it. If any parts don't exist (from, to or the relation), creating a relationship will fail. You can inspect the returned `relationship` object to find errors:

~~~ ruby
p relationship.errors.full_messages
~~~

KOR doesn't prevent you from creating several identical relationships, so you might want to add a condition, like so:

~~~ ruby
unless Relationship.related?(from.id, 'has created', to.id)
  .. create the relationship
end
~~~

**Comment by Diederka** [comment]
Thank you!
