### ISSUE TITLE
how to build a realtionship WHILE importing 

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#166]
we have changed our metadata schema to be more clean. 
so now we have places within places instead of a place with a distinct nakme of a specified place. 
both places are in the source excel. but how can I make the relationship within one kind (place) by importing? 
until now we used the following scripts for place  
wth columns 5 for example has the place "edzna" , column 6 has the place "Entrance to the archaeological zone"  (which is a location in edzna).  : 

```
`Artefact -> Place
--
KOR_ROOT="/home/kor/kor/"
# artefact_is_located_in_place.rb
# loading the rails environment
require "#{KOR_ROOT}/config/environment"
 
default = Collection.where(:name => 'default').first
place = Kind.where(:name => 'Place').first
artefact = Kind.where(:name => 'Artefact').first
 
relationship =
artefact.entities.each do \|artefact_entity\|
place.entities.where(:distinct_name => artefact_entity.dataset['artefact_is_located_in_place']).each do \|place_entity\|
puts "SUCCESS"
Relationship.relate_and_save(artefact_entity, "artefact is located in place", place_entity)
end
end

Place
--
KOR_ROOT="/home/kor/kor/"
# import_Place+Relation.rb
# loading the rails environment
require "#{KOR_ROOT}/config/environment"
require 'json'
default = Collection.where(:name => 'Guest Collection').first
document = Kind.where(:name => 'Place').first
File.read("/home/kor/sourceFiles/source_import_20.04.csv").split("\n")[1..-1].each do \|line\|
fields = line.split(";")
jsonData = "{\"place_in_twkm_database\" : \"" + fields[7] + "\",
\"place_locates_holder\" : \"" + fields[8] + "\", \"place_locates_artefact\" : \"" + fields[16] + "\", \"place_was_visited_by_person\" : \"" + fields[25] + "\"}"
jsonObj = JSON.parse(jsonData)
puts jsonData
work = Entity.new(
:kind => document,
:collection => default,
:name => fields[5],
:distinct_name => fields[6],
:dataset => jsonObj
)
if work.valid?
p work
work.save
else
p work
p work.errors.full_messages
end
end



`
```

but now the place in row 6, which was the distinct nae, shall be the Place in the place .
with relations like 
" \"place_locates_place\" : \"" + fields[6] + "\",\"place_is_located_in_place\" : \"" + fields[5] + "\" "

but how can I establish this realtion by importing?

**Comment by moritzschepp** [comment]
What about something like this:

~~~ ruby
places = Kind.where(name: 'Place').entities
places.each do |place|
  if other_name = place.dataset['place_is_located_in_place']
    if other_place = places.where(name: other_name).first
      Relationship.relate_and_save(place, 'is located in', other_place)
    else
      raise "place #{other_name} not found"
    end
  end
end
~~~

?

**Comment by Diederka** [comment]
Thanks. I looks good. But I didnt know how to properly set into my import skript. 
It ran but didnt establish relationsships.

**Comment by MaximilianBrodhun** [comment]
Are you sure that this line really works?

`places = Kind.where(name: 'Place').entities`

With ruby Version 2.2.6p396  we get the error message that entities ist not a method for Kind in ArctiveRecords. Do we need to upgrade Ruby?

**Comment by moritzschepp** [comment]
No there is a typo, I corrected it in my post above. Its 

    places = Kind.where(name: 'Place').first.entities

**Comment by MaximilianBrodhun** [comment]
Thanks alot!
