### ISSUE TITLE
Title "additional criteria" better be named "Search Relations" or only "Relations"

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#169]
**_Is the following for a pull request? Or is this only interesting for us?_** 
We would like to change the following field name: 
When using the expert search, there is a field titled "additional criteria" 
you can search there for relations or (established relationships)  between respective entity type (established entity) . 
Thus we would prefer the title "Search Relations" or only "Relations" here.

**Comment by moritzschepp** [comment]
I think this is a question for @wuebbena. Also consider the German version of the field label.

**Comment by wuebbena** [comment]
I would consider this a reasonable clarification, whereby I would avoid the term "Search" at this point and would only prefer "Relations" or "Relationships" or something like this. And then we could choose "Verknüpfungen" instead of "Weitere Kriterien" in the german version.

**Comment by Diederka** [comment]
@wuebbena:  I also agee with "and would only prefer "Relations" or maybe "Relationships" or "Entity's Relations"...
Will the changes be in the code of the next kor version?
