### ISSUE TITLE
Images are not displayed via Internet Explorer

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#189]
I got an email from a user, that he is not able to see the images on our database - just a cross where the image should be. 
https://classicmayan.kor.de.dariah.eu/

I found out, he was using IE. 
How can this be fixed?

**Comment by moritzschepp** [comment]
What version of IE is this?

**Comment by moritzschepp** [comment]
@wuebbena, I remember discussing the issue with you many years back. At the time we decided not to make the software IE compatible because the market share is very low. Is that still what you think?

**Comment by Diederka** [comment]
Oh I am totally with you there. 
I was not sure - it seemed a little unpolite - but I nevertheless answered in the first place that it would be one solution to use a different browser. 
but now  in any case I have an official news from the developers to give.

**Comment by moritzschepp** [comment]
For older versions of IE, you can add a HTTP header to the apache configuration:

    Header set X-UA-Compatible: IE=Edge

**Comment by moritzschepp** [comment]
Kor adds the http header now (kor > v4)
