### ISSUE TITLE
adding one artefact via clipborad to own group seems to have a bug

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#191]
I tried to add just one selected Artefact entity to a group (to use it for producing slides ... )
I selected it, put it to the clipboard, from there I put it into a newly created personal group. but a whole bunch of artefacts went into that group too. thus it is full now with several artefact entities.
watch my group, it should only have the entity: Xcalumkin, Column 2 (XLM: Col. 2). : 
https://classicmayan.kor.de.dariah.eu/user_groups/16
or 
https://classicmayan.kor.de.dariah.eu/pub/1/01384c49b6f3

**Comment by Diederka** [comment]
I tried it again, now really with an empty clipboard. then i added only one element. Stela 1. 
still the same bug: there is a stela 2 added somehow. 
see: https://classicmayan.kor.de.dariah.eu/pub/1/2650574b74b7

**Comment by moritzschepp** [comment]
Under the link I just see "Arroyo de Piedra, Stela 1". Did you remove the other one already or does it still show up?

**Comment by Diederka** [comment]
I don't remember the specific scenario here. But due to the flag "verfification needed" I answer: I think all problems got solved here too, because you explained it to me in the related issue #192.

**Comment by moritzschepp** [comment]
Thanks for the finalizing comment. I close the issue.
