### ISSUE TITLE
if I try to zip and download the group I created, it is said:  "There are no entities to download in this group"

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#192]
This issue is maybe related somehow to issue #191

if I try to zip and download the group I created, it is said: 
`"There are no entities to download in this group" `
bu why? it comprises already are several entities. 
see group: 
https://classicmayan.kor.de.dariah.eu/user_groups/16
or 
https://classicmayan.kor.de.dariah.eu/pub/1/01384c49b6f3

**Comment by moritzschepp** [comment]
The zip download grabs all media in a group and wraps them in a zip file. If there is no media, then the message above is shown. The idea of this feature was to have a simple way of downloading images for presentations or publications.

**Comment by Diederka** [comment]
Okay, I get it. There were only entities connected to media. 
I created one with one artefact AND some media. Fortunaltely now the download is not only possible, but also the metadata in txt-format is appended. and there the connection of artefact to media ist described, which is very beneficial. 
That is a good feature. But I these things are difficult to find out. I hink it's a pity that the documentation is missing or difficult to find.

**Comment by Diederka** [comment]
I hope in the future there will be a more thoroughly written documentation. maybe our project and others using kor can help with our own parts of documentations.

**Comment by moritzschepp** [comment]
Let me clarify: The download should include all media from that group (there are a few limits on the amount and the kind of download which you can configure in the admin section) and some metadata for the medium's "neighborhood". Is this not what it is happening in your installation?

Yes the state of the documentation is a disgrace. We'll try to work on it. Of course, if you have anything to contribute, I'd be happy to integrate it. Just let me know.

**Comment by Diederka** [comment]
Hmm. 
Okay I tried it again. 
The actual content of my zipped and downloaded group seems to be fine. (though really ortherwise displayed in the browser). 
But thats okay by me. 
So if I mark 4 media, and their artefacts, they get downloaded. 
in the metadata the respective medium uuid is listed, then the of the artefact is listed and all connected media to the artefact (which are not downloaded) are listed, which is fine. 

But another specific question to your remark about the admin section: 
I can only find this there: 
```
Maximum download size for foreground groups in MB
10
Maximum file size for uploads
1000
Number of recent entities
10
```
The download is only limited in the size of data (im MB), but what do you mean with kind of download? 
And what does "Number of recent entities" actually mean? 

PS: Yes, I try to create a documentation of our work with kor and our archive. But I have a hard time with the technical description of the database and also with the features that exist. ...
I opened this issue for that #195

**Comment by moritzschepp** [comment]
When you click on the zip download link, kor builds the zip file during the web request (so the browser simply appears to be loading during this process). Depending on the available server hardware and the group size, this can take a long time. `Maximum download size for foreground groups in MB` configures the maximum group size that can be downloaded in this way. For larger groups, the user immediately gets a message that the zip is being created and he receives an email with a download link once its available.

The `Number of recent entities` is a legacy configuration option. Make sure its > 1 but otherwise you can ignore it.
