### ISSUE TITLE
Import erlangen crm

### ISSUE THREAD

**Issue by MaximilianBrodhun** [coneda/kor#193]
In your presentation http://www.adwmainz.de/mediathek/medien/ansicht/conedakor-von-der-tabelle-zum-netzwerk-vortrag-von-moritz-schepp-und-thorsten-wuebbena.html you explain how to use erlangen crm to give the data a semantic.

Where can I find the file for the import of erlangen crm like descriped in the video near to minute 17?

**Comment by moritzschepp** [comment]
The feature is available in the v3.0 branch here on github. This is the dev branch for the next major release. With that, you can run `bundle exec bin/kor import-erlangen-crm`

**Comment by MaximilianBrodhun** [comment]
Thanks alot for this information.
Is there any plan when the next major release will be released?

**Comment by wuebbena** [comment]
I don't want to stick my neck out for taht but I guess we coulfd make it in September? wdyt @moritzschepp ?

**Comment by moritzschepp** [comment]
So in the v3.0.0 milestone, all tickets are actually closed (they don't show as closed because github only does that when the branch is merged into the master branch). The only one left is #120 but its a small thing. If you are happy with the quality control via other projects, @wuebbena, then I can wrap it up next week.

**Comment by wuebbena** [comment]
"Holzhausen" runs fine, so I would give the go-ahead for the release. @moritzschepp https://issues.dfkg.org/issues/1339 is on your radar? Probably there is potential for conflict?

**Comment by moritzschepp** [comment]
What kind of conflict? The issue represents (in more detail) #53. You mean the mirador code?

**Comment by wuebbena** [comment]
@MaximilianBrodhun v3.0 is released.
