### ISSUE TITLE
About a documentation or a user manual for conedakor 

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#195]
I try to create a documentation of our work and about handling kor front and backend for our mayan image archive. thus the users know how to use the database. But I have a hard time with the technical description of the database... 
But apart from the main help text on our website which shows our metadata and some basic information -> https://classicmayan.kor.de.dariah.eu/static/help
I only wrote some help texts for at least fr the search functions , clipboard and login. 
For example I wrote the Help sections for search and expert search. some things are written in your documentation but it is more of a stub. 
So I am still not sure, what else the search can offer.  
See: my text for  the pop up behind the "?"
> Simple Search
Searching the Maya Image Archive is performed by a full-text search of all its contents. 
Simple Search within Entity Types The database of the Maya Image Archive contains the following entity types: “Archaeological Site”, “Artefact”, “Collection”, “Holder”, “Medium”, “Person”, “Place”. Searches can be conducted within either all entity types (“All”), or within a single entity type by choosing the respective entity type from a dropdown menu in the field “Entity Type”. This dropdown menu lists the entity types in alphabetical order. 
Search Terms
The Simple Search is automatically right-truncated. Entering an operator such as the asterisk is not necessary. Multiple search terms (keywords) can be entered into the field “Search Term”. These search terms are automatically linked via the relation AND. 
This means that, if conducting a search by entering a search term, e.g. "museum", this term is retained and appears below the field “Search Term”. If entering another search term, e.g. "Edzna", both terms are linked by the relation AND. Thus, only contents that contain both terms “museum” and “Edzna” are retrievable by this search. The apposition of multiple AND relations further limits the number of search results. 
Note: 
Media cannot be searched by title or properties or relationships. However, they can be searched in the expert search via their UUID (their database identifier). The UUID of each medium can be found under the listed metadata in their "master data" section. It can be downloaded by clicking on "meta data", in the download area of each medium. 

> Character Recognition 
The search function does not distinguish between lower and upper case. Diacritics on vowels or consonants, or diareses are either ignored in the search, or attributed to their associated vowel or consonant. Thus, after entering e.g. “Hecelchakán” or “Hecelchakän” or “Hecelchakan”, the search always retrieves “Hecelchakan”. 
More specific searches are possible via the advanced Expert Search. Click:-> Expert Search 

> Search Results List 
Search results are listed on the right of the results page. The entity type is listed in italics below its title. If multiple entities have been found, they can be browsed by clicking the arrow symbol on the upper right. Further, a specific page number can be entered into the field next to “go to page”. The search results are listed as entities in alphabetical order with a maximum of 10 results to be shown on a single page. Each result shows an entity together with a selection of its associated media. Clicking on the retrieved entity leads to the entity’s view page where all relationships of the entity are displayed and clickable. To return to the search results list, click the “back” button. 

> Using the clipboard (Only for logged in Users): 
For logged in users Entities can be copied to the clipboard using the button to the left of the titles. From the Clipboard you have several possibilities to edit the data. The clipboard is a means to create own private user collections within the database.

or: 

> Expert Search
Searching the Maya Image Archive is performed by a full-text search of its contents. 
Expert Search within Collections 
Without login only the "guest collection" is searchable. 
For logged in Users: Either all collections can be searched at once, or specific collections can be searched individually. Individual collections can be selected for a search by clicking the Pencil Button, and checking the box of the desired collection. 
Expert Search within Entity Types 
The database of the Maya Image Archive contains the following entity types: “Archaeological Site”, “Artefact”, “Collection”, “Holder”, “Medium”, “Person”, “Place”. In addition to a Simple Search (search within all (“All”) entity types or only a single entity type selected from a dropdown menu), the Expert Search offers further search options: If a specific entity type has been selected, further search fields appear. Each one of these search fields can be searched. Such a search is more specified specified and thus further limits the search results. If e.g. the entity type “Artefact” has been selected, the following search fields appear and can be searched: 
Entity Type Name / Title / UUID Dating Further Properties Tags Artefact Type Artefact in TWKM Database Catalogue Number Publication Zotero Publication ID Inventory Number Artefact Type in TWKM Database 
Note:
If the entity type “all” is selected, only fields that all entities contain can be searched. These are: "Name / Title / UUID", "Dating", "Additional Criteria", Tags.
Expert Search by Relationships 
A special feature offered by the Expert Search is the search for relations via the search field “Relationships”. This type of search puts an entity type in relation to other entity types. This means, that, if a specific entity type is chosen, all its possible relations to other entities can be searched. If an entity type, e.g. “Person”, is chosen, criteria such as “created medium”. can be searched. 
Search Terms
The Expert Search is automatically right-truncated. Entering an operator such as the asterisk is not necessary. 
Note: 
Media cannot be searched by title or properties or relationships. However, they can be searched in the expert search via their UUID (their database identifier). The "UUID" of each medium can be found under the listed metadata in their "master data"" section. It can be downloaded by clicking on "meta data"", in the download area of each medium. 
Character Recognition 
The search function does not distinguish between lower and upper case. Diacritics on vowels or consonants, or diareses are either ignored in the search, or attributed to their associated vowel or consonant. Thus, after entering e.g. “Hecelchakán” or “Hecelchakän” or “Hecelchakan”, the search always retrieves “Hecelchakan”. 
Search Results List 
Search results are listed on the right of the results page. The respective entity type is listed in italics below its title. If multiple entities have been found, they can be browsed by clicking the arrow symbol on the upper right. The search results are listed in alphabetical order with a maximum of 10 results to be shown on a single page. Clicking on the retrieved entity leads to this entity’s view page. To return to the results list, click the “back” button of the browser. Clicking on the retrieved entity leads to the entity’s view page where all relationships of the entity are displayed and clickable. To return to the search results list, click the “back” button. 
Using the clipboard (Only for logged in Users): 
For logged in users Entities can be copied to the clipboard using the button to the left of the titles. From the Clipboard you have several possibilities to edit the data. The clipboard is a means to create own private user collections within the database.

> Character Recognition 
The search function does not distinguish between lower and upper case. Diacritics on vowels or consonants, or diareses are either ignored in the search, or attributed to their associated vowel or consonant. Thus, after entering e.g. “Hecelchakán” or “Hecelchakän” or “Hecelchakan”, the search always retrieves “Hecelchakan”. 
More specific searches are possible via the advanced Expert Search. Click:-> Expert Search 

> Search Results List 
Search results are listed on the right of the results page. The entity type is listed in italics below its title. If multiple entities have been found, they can be browsed by clicking the arrow symbol on the upper right. Further, a specific page number can be entered into the field next to “go to page”. The search results are listed as entities in alphabetical order with a maximum of 10 results to be shown on a single page. Each result shows an entity together with a selection of its associated media. Clicking on the retrieved entity leads to the entity’s view page where all relationships of the entity are displayed and clickable. To return to the search results list, click the “back” button. 

Using the clipboard (Only for logged in Users): 

>For logged in users Entities can be copied to the clipboard using the button to the left of the titles. From the Clipboard you have several possibilities to edit the data. The clipboard is a means to create own private user collections within the database.

also texts for clipboards etc are to be done before the first users login and use that features... 
for now  only have : 

And for login: 
>Login All media and information presented in the Maya Image Archive can be accessed without login. Further, users may enter the database as Registered User or via Federated Login into the database. Federated Login is available for users with a DARIAH-account. Users entering the Maya Image Archive as Registered User or via Federated Login are granted specific editorial rights. These rights include creating their own collections within the archive, and entering additional information to enrich the database.

for clipboard: 
> Here you can see what is in your Clipboard. From the Clipboard you have several possibilities to edit the data. (Only for logged in Users, Editors and Admins.) Entities can be copied to the clipboard using the button to the left of the titles. The clipboard is a means to create own private user collections within the database. From here you can collect, connect and edit selected entites.

and the rest still is unsufficiently explained 

I plan to publish the documentation though in future times, and I hope you can reuse some things for kor. I also hope you @moritzschepp and @wuebbena  can edit incorrect facts. 
I will keep you postet

**Comment by moritzschepp** [comment]
Oh this is great, thanks a lot! I will probably copy this to https://github.com/coneda/kor/blob/master/DOCS.md. Its really an excellent starting point.

If you think, something should be changed, don't hesitate to open tickets about it or to send pull requests.

**Comment by wuebbena** [comment]
@Diederka That's really great. Thank you so much for sharing this helpful information.

**Comment by moritzschepp** [comment]
I have just integrated this in [DOCS.md](https://github.com/coneda/kor/blob/master/DOCS.md) and I could use a lot of it. Thanks again!
