### ISSUE TITLE
rethink groups, collections and user groups

### ISSUE THREAD

**Issue by moritzschepp** [coneda/kor#199]
The naming for groups, collections and user groups is at least confusing:

* groups refer to n-n entity containers (there are various types like "user groups", meaning: groups controlled by a specific user)
* collections refer to 1-n entity containers, controlling access to entities
* user groups refer to n-n containers for users, controlling access by users

So collections are a tool to control permissions but often, they carry content information, such as project name, licence etc. The involved objects should be named more clearly. I discussed two possible solutions with @wuebbena:

1. _Assume that collection names will always carry content information_: This entails keeping the collection selector in the search for end users, because the information (for example a license name) might be important to filter for. We should then use a name that makes sense there, possibly "scope", "zone" or "realm".

2. _Prevent that collection names carry content information_: The collection selector could be removed from the search (for non-editors) but the information encoded in the collection name would have to be duplicated in adequate fields. Think about the use case of licenses. The term "collection" could then simply be changed to "groups" (since that is the term associated with permission management) and the "groups" could be relabeled "collections".

**Comment by wuebbena** [comment]
@fabiancremer Any opinion on that?

**Comment by moritzschepp** [comment]
Thanks for your input, @Diederka, you are very welcome to comment on any issue! Do you have a preference for what new labels to choose?

**Comment by Diederka** [comment]
Thanks. And Thanks for asking me.
Hmmm. I basically agree with you @moritzschepp : The term "collection" could then simply be changed to "groups" (since that is the term associated with permission management) and "groups" could be relabeled "collections" or "digital collections."

**Comment by wuebbena** [comment]
I'd be okay with that, too. 
However, in my opinion, we should definitely take this opportunity to think about the possibility of also giving an indication of the legal situation of the entity (mainly in the case of "medium"). 
As described above by @moritzschepp : "the information encoded in the collection name would have to be duplicated in adequate fields. Think about the use case of licenses."
Because only then would the situation occur that we could find all media that are under a certain license. The groups (the new ones) would not help us here.

But I've just talked with @fabiancremer and he wants to contribute his opinion as well.

**Comment by Diederka** [comment]
@wuebbena  @moritzschepp @fabiancremer. You are right. good idea. Our database will profit from it. Because we also plan to provide restricted licensed Media in the near future (we plan something like giving access only for logged in persons.)

**Comment by moritzschepp** [comment]
Just to describe the use-case of licenses: Let's say medium A is published under CC BY-SA and medium B is published under CC BY-NC-ND 4.0. In KOR up to version 3.0.0, you could

Create two collections, named "CC BY-SA 2.0" and "CC BY-NC-ND 4.0", grant public read access to them and put the media into the collections according to the license. Now, access is controlled by collection membership of the medium but the only way to know a medium's license is also the collection membership: If you want to list all "CC BY-SA 2.0" licensed media (e.g. because you want to show only media which is free to be used in a commercial context), you would effectively want to filter by collection.

Alternatively, you could create a collection "public read access", grant appropriate access and put both media into it. Additionally, you add a field "license" to the media entity type and fill it in with the license for each medium. Now, if you want to do the same search as above, you could search by field value (similar to a search by ISBN).

The license use-case is a bit artificial in a way because you can't search by medium yet, but there is good reason to change that (e.g. #135 and perhaps #159 and #190). You can also construct a similar case with Project-Collections.

**Comment by wuebbena** [comment]
As you write, it is important to link the topic of the collections not only with the license question, but also with the permission to access them. Since we have more cases than "read" or "don't read", but also "read" and "don't write", "read" and "write" etc. it is important that we think carefully about what we do here, because the user-rights don't necessarily correlate 1:1 with license or rights questions of the entities.
The idea with the license field on the entity makes sense to me in terms of the search.

**Comment by moritzschepp** [comment]
Yes, @wuebbena, exactly. So it seems **you both prefer option 2** from above (I just wanted to state this clearly so that we see it immediately as the result of the discussion).

**Comment by wuebbena** [comment]
But let's wait for @fabiancremer 's testimony.

**Comment by fabiancremer** [comment]
I would also advocate for option 2. The most important thing would be to seperate licenses (information for external reuse) and access (rights in the current database).

You may prevent using collections for content tagging, but they are information carrier for the administrative level - which can be usefull for all editors, potentially for all registreted users with write access somewhere. So I would not remove the collection selector in expert search for all but admins.

Suggestion for naming:
User Groups -> User Groups | Nutzergruppen (that's what Windows, OwnCloud use)
Collections -> Domains | Domäne (that's what Windows and the internet uses for access rights)
Groups -> either Collections | Kollektionen (like e.g. flickr) or Sets | Sets or Compilation | Kompilation

**Comment by wuebbena** [comment]
> So I would not remove the collection selector in expert search for all but admins.
> 
Just to clarify it here, you really wouldn't remove the selector or was the "not" just sneaking in by mistake?

**Comment by fabiancremer** [comment]
To clarify: I see no logical reason to remove the "collection" selector for users with editing rights.

**Comment by moritzschepp** [comment]
Hey @fabiancremer, great naming suggestions! We'll take that :)

**Comment by wuebbena** [comment]
We will proceed here as suggested above (see https://github.com/coneda/kor/issues/199#issuecomment-425336617).
The new "Domains | Domäne" (Ex-collection | Ex-Sammlung) are no longer determined by content, but by the legal situation of the content stored in them (CC-BY-SA etcetera).
What is now still called a "group | Gruppe" will then become a "collection | Sammlung" and content that belong together for curatorial reasons is stored there.
