### ISSUE TITLE
Mirador: Showing Name of Institution and Collection in Mirador: 

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#209]
When I load images from our Maya Image Database into the Viewer and compare them with images from other image collections, I discover that our database still runs under the name: "Thorstens Schatulle" (see screenshot) 
<img width="1303" alt="mirador-viewer-vergleichendesicht" src="https://user-images.githubusercontent.com/25532142/52773557-88edcb80-303b-11e9-8e34-56790a657e25.png">
I had to smile for a moment, but of course it would be better if our database and institution could be named there. 
It would be good if there were something like that: 
### University of Bonn. 
And then to the database: 
### Project Text Database and Dictionary of Classic Mayan: The Maya Image Database. 
How can we manage that?

**Comment by moritzschepp** [comment]
:) That's in acknowledgement of @wuebbena's ongoing contribution to this piece of software, so it can't be removed!

... just kidding. Perhaps the most reasonable thing to set as a value would be the site maintainer? In your case, this is **Textdatenbank und Wörterbuch des Klassischen Maya - Arbeitsstelle der NRW Akademie der Wissenschaften und der Künste**. What do you think?

**Comment by wuebbena** [comment]
> :) That's in acknowledgement of @wuebbena's ongoing contribution to this piece of software, so it can't be removed!
> 
 I am moved to tears. :-)

**Comment by Diederka** [comment]
I agree. On the Website it is as well:  
### Textdatenbank und Wörterbuch des Klassischen Maya - Arbeitsstelle der NRW Akademie der Wissenschaften und der Künste
