### ISSUE TITLE
"create entity" selectbox not styled correctly

### ISSUE THREAD

**Issue by moritzschepp** [coneda/kor#212]
v4.0.0: ![bildschirmfoto 2019-02-22 um 08 31 03](https://user-images.githubusercontent.com/506366/53256666-43ee1880-367d-11e9-93a3-7aa7d25f5b54.png)

v2.1.1: ![bildschirmfoto 2019-02-22 um 08 33 08](https://user-images.githubusercontent.com/506366/53256675-47819f80-367d-11e9-8872-df481866bfb7.png)

**Comment by moritzschepp** [comment]
@wuebbena which os and browser did you use?

**Comment by wuebbena** [comment]
FF 65.0.1 / MacOS 10.14.3
