### ISSUE TITLE
Question: is it possible to mass edit global groups via script?

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#222]
I have a just question about the management of Groups like Global Groups. 
These are called authority_groups I reckoned via the URL or via Mysql requests 
I tried to find out via MySQL how they were connected to the media (if a medium were assigned to a global group), but at first sight I didn't find the connection. 
So I don't know how to edit it. 
I ask because I would like to do a mass edition: 
I would like to make a mass allocation of certain media to a global group (until now they dont belong to any Group).   
Can I use ruby script to assign all the media I have uploaded so far (or even better, all the media whose filename begins with "KHM") to a certain global group that I have created, which also has a hierarchy.  (Maya Image Archive - Karl Herbert Mayer Image Archive ) actually, I want to assign them to the lowest hierarchy of the hierarchy. -> https://classicmayan.kor.de.dariah.eu/authority_groups/2

**Comment by moritzschepp** [comment]
Yes sure that's possible:

In MySQL terms, an entity is in an authority group if there exists a record in the table `authority_groups_entities` linking them. This is called a "join table". You can add or remove from that table with SQL queries. Make sure not to add duplicate entries.

In ruby scripts, this is achieved like this:

~~~ruby
# get the entity (depending if you have a medium_id or a entity_id)
entity = Medium.find(12345).entity
entity = Entity.find(56789)

# get the authority group
authority_group = AuthorityGroup.find_by!(name: 'my group')

# add the entities
authority_group.add_entities(entity)
~~~

This avoids duplicates for you.

**Comment by moritzschepp** [comment]
Sorry, just saw your specific problem. To do this with many entities, you first have to grab a hold of them, potentially filter them and then add them to the group like this:

~~~ruby
# to find all medium entities
entities = Entity.media

# to filter them by some filename pattern
entities = entities.to_a.select do |entity|
  entity.medium.original.original_filename.match(/^KHM/)
end

# get the authority group
authority_group = AuthorityGroup.find_by!(name: 'my group')

# add the entities
authority_group.add_entities(entities)
~~~

The exact code depends a bit on the ConedaKOR version you are using, let me know if it doesn't work.

**Comment by Diederka** [comment]
Thank you very much. The code snippets worked both perfectly!
I used your first proposed code to connect just one specified entity person named "Karl Herbert Mayer" to a global group. It worked fine. 
The next code snippets for the mass edition of the 6000 media worked as well. 
I just needed to set the environment before - the rest was your code - like so: 
`
KOR_ROOT="/home/kor/kor/"
# loading the rails environment
require "#{KOR_ROOT}/config/environment"
entities = Entity.media
# to filter them by some filename pattern
entities = entities.to_a.select do |entity|
  entity.medium.original.original_filename.match(/^KHM/)
end
# get the authority group
authority_group = AuthorityGroup.find_by!(name: 'Karl Herbert Mayer Image Archive')
# add the entities
authority_group.add_entities(entities)`


Just a curious question: I thougth in a Regex the ^ means "everything except". but we searched the pattern KHM and it worked. 
Is there a reference for Regexs used in ruby you could recommend, which I could look up for creating some patterns? is this a good one: 
https://rubular.com/
Again, thanks!

**Comment by moritzschepp** [comment]
No problem, glad it worked.

`^` means "except" only in a character class, e.g. `/[^aeiou]/` matches non-vowels. Otherwise, it means "beginning of the line" which is what we used above: `/^KHM/` matches `KHM1234` but not `1234KHM`.

Rubular.com is great page I use regularly. If you want to know all the details, there is the official ruby documentation, specifically for the `Regexp` class: https://ruby-doc.org/core-2.5.5/Regexp.html.

**Comment by Diederka** [comment]
Super. Thanks again!
