### ISSUE TITLE
create user without sending credentials via mail

### ISSUE THREAD

**Issue by moritzschepp** [coneda/kor#227]
The use case is to create accounts for other people (possibly many at a time). In this case we want to set the password to a known value so that we can communicate it to the users via some other channel. The system therefore should not send an email automatically.

@wuebbena, sounds good?

**Comment by wuebbena** [comment]
Sounds terrific, this solution would give the administration much more flexibility.

**Comment by moritzschepp** [comment]
I knew you'd like it ;)
