### ISSUE TITLE
Question: How to let other institutions only harvest a specific global group (authotithy_group) via OAI-PMH? 

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#233]
We plan to let the DDB use our metadata in the future. 
My question out of interest: 
When they will harvest our metadata via OAI API, how can it be managed to only let them harvest the following global group? 
What's the verb to request that?
https://classicmayan.kor.de.dariah.eu/authority_group_categories/2

*For now I only know how to request for all entities, kinds, relations and relationships... 
like so: 
https://classicmayan.kor.de.dariah.eu/api/oai-pmh/relationships.xml?verb=ListRecords&metadataPrefix=kor
https://classicmayan.kor.de.dariah.eu/api/oai-pmh/relations.xml?verb=ListRecords&metadataPrefix=kor
https://classicmayan.kor.de.dariah.eu/api/oai-pmh/entities.xml?verb=ListRecords&metadataPrefix=kor
https://classicmayan.kor.de.dariah.eu/api/oai-pmh/kinds.xml?verb=ListRecords&metadataPrefix=kor

**Comment by moritzschepp** [comment]
Global groups don't provide any access control, only collections do. If you would like to give access only to a part of the entities via OAI-PMH, put them in a separate collection and give access only to that collection.

Should the DDB be blocked from reading other records or should they simply know that records are in that group?

**Comment by Diederka** [comment]
They should be blocked. Because only the records in our Image Archive Group are our own and their rights are clear which means, they are under a free license. some others are from external collections, which we added manully. 
So I reckon the solution will be: 
I will have to move the external data to our Login-Collection. And the majority of data (which is to be published in the DDB) will stay in our guest collection, the collection which needs no login.

**Comment by moritzschepp** [comment]
Yes, that sounds right.
