### ISSUE TITLE
Editing seems not possible at the moment because of some kind of timeout 

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#234]
I tried to create a generator field for the field "culture" (useful only for the ddb when searching for culture "Maya". )
I first wanted to rename the field "culture" in culture_in_AAT". It didn't work 
Then I tried to create  the following generator instruction: 
~~~html
<span ng-if="entity.culture_in_AAT">
  <a href=http://vocab.getty.edu/page/aat/{{entity.dataset.culture_in_AAT}}">
>> Culture in Getty Art & Architecture Thesaurus Online
  </a>
</span>
~~~
It also didn't work. 
There was no sign for timeout, but the browser seems to freeze while it obviously is processing something. 
What can I do?

**Comment by wuebbena** [comment]
<span ng-if="entity.dataset.culture_in_AAT"> 
<a href="http://vocab.getty.edu/page/aat/{{entity.dataset.culture_in_AAT}}" target='_blank'>» Culture in Getty Art & Architecture Thesaurus Online</a>

**Comment by moritzschepp** [comment]
Make sure to use `»` instead of `>>`.

**Comment by wuebbena** [comment]
~~~
<span ng-if="entity.dataset.culture_in_AAT">
  <a href="http://vocab.getty.edu/page/aat/{{entity.dataset.culture_in_AAT}}">
» Culture in Getty Art & Architecture Thesaurus Online
  </a>
</span>
~~~
This is how it should look. An opening quotation mark and a "dataset" were missing.

**Comment by Diederka** [comment]
Oh, sure i erased the dataset while cropping code. But, I would have found out about the missing dataset as soon as no link were visible after saving the generator code and looking it up on the artefact page. But that was not the problem.
The problem seems to be, that no edition (wrong or right) is possible at all. 
Still, I am not able to even save the wrong generator code. And I am not able to edit the field name There always is a sign which indicates, that it is processing, but that never comes to an end (see arrow in first image). 
Maybe there is something wrong with the server? 
<img width="1118" alt="Screenshot 2019-04-17 10 54 54" src="https://user-images.githubusercontent.com/25532142/56275179-760d7b00-6100-11e9-9e9d-8549b4a4fda7.png">
<img width="1087" alt="Screenshot 2019-04-17 10 56 11" src="https://user-images.githubusercontent.com/25532142/56275184-786fd500-6100-11e9-8338-27f7514956f7.png">

**Comment by moritzschepp** [comment]
I see. There should indeed be more information in the production.log file. Can you post the relevant part?

**Comment by Diederka** [comment]
Okay, ia on holidays and no IT specialist here. But I tried it myself to read the logfile. Is this the part, which you need, or ist it more log entries ? (cause there are plenty of before).

`I, [2019-04-18T16:15:56.872606 #18702]  INFO -- : Completed 200 OK in 30ms (Views: 21.3ms | ActiveRecord: 3.8ms)
I, [2019-04-18T16:15:59.085941 #18200]  INFO -- : Started GET "/kinds/3?include=fields%2Cinheritance" for 80.145.245.69 at 2019-04-18 16:15:59 +0200
I, [2019-04-18T16:15:59.086060 #18702]  INFO -- : Started GET "/kinds/3/fields/types" for 80.145.245.69 at 2019-04-18 16:15:59 +0200
I, [2019-04-18T16:15:59.087706 #18200]  INFO -- : Processing by KindsController#show as JSON
I, [2019-04-18T16:15:59.087789 #18702]  INFO -- : Processing by FieldsController#types as JSON
I, [2019-04-18T16:15:59.087849 #18200]  INFO -- :   Parameters: {"include"=>"fields,inheritance", "id"=>"3", "kind"=>{}}
I, [2019-04-18T16:15:59.087903 #18702]  INFO -- :   Parameters: {"kind_id"=>"3", "field"=>{}}
I, [2019-04-18T16:15:59.094717 #18702]  INFO -- :   Rendered fields/types.json.jbuilder (0.2ms)
I, [2019-04-18T16:15:59.094861 #18702]  INFO -- : Completed 200 OK in 7ms (Views: 0.6ms | ActiveRecord: 1.1ms)
I, [2019-04-18T16:15:59.095745 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.2ms)
I, [2019-04-18T16:15:59.096057 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.2ms)
I, [2019-04-18T16:15:59.096335 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.2ms)
I, [2019-04-18T16:15:59.096611 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.2ms)
I, [2019-04-18T16:15:59.096882 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.1ms)
I, [2019-04-18T16:15:59.097146 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.1ms)
I, [2019-04-18T16:15:59.097411 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.2ms)
I, [2019-04-18T16:15:59.097677 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.2ms)
I, [2019-04-18T16:15:59.097954 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.2ms)
I, [2019-04-18T16:15:59.098209 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.1ms)
I, [2019-04-18T16:15:59.098476 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.2ms)
I, [2019-04-18T16:15:59.098749 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.2ms)
I, [2019-04-18T16:15:59.099001 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.1ms)
I, [2019-04-18T16:15:59.099265 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.1ms)
I, [2019-04-18T16:15:59.099530 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.2ms)
I, [2019-04-18T16:15:59.099784 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.1ms)
I, [2019-04-18T16:15:59.100093 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.1ms)
I, [2019-04-18T16:15:59.100249 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.0ms)
I, [2019-04-18T16:15:59.100417 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.0ms)
I, [2019-04-18T16:15:59.100567 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.0ms)
I, [2019-04-18T16:15:59.100733 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.1ms)
I, [2019-04-18T16:15:59.100900 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.1ms)
I, [2019-04-18T16:15:59.101050 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.0ms)
I, [2019-04-18T16:15:59.101207 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.0ms)
I, [2019-04-18T16:15:59.101353 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.0ms)
I, [2019-04-18T16:15:59.101508 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.1ms)
I, [2019-04-18T16:15:59.101664 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.0ms)
I, [2019-04-18T16:15:59.101821 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.0ms)
I, [2019-04-18T16:15:59.101963 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.0ms)
I, [2019-04-18T16:15:59.102116 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.0ms)
I, [2019-04-18T16:15:59.102263 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.0ms)
I, [2019-04-18T16:15:59.102402 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.0ms)
I, [2019-04-18T16:15:59.105023 #18200]  INFO -- :   Rendered kinds/_customized.json.jbuilder (11.1ms)
I, [2019-04-18T16:15:59.106081 #18200]  INFO -- :   Rendered kinds/show.json.jbuilder (12.3ms)
I, [2019-04-18T16:15:59.106215 #18200]  INFO -- : Completed 200 OK in 18ms (Views: 11.6ms | ActiveRecord: 2.2ms)
I, [2019-04-18T16:16:10.168061 #18200]  INFO -- : Started PATCH "/kinds/3/fields/105" for 80.145.245.69 at 2019-04-18 16:16:10 +0200
I, [2019-04-18T16:16:10.169739 #18200]  INFO -- : Processing by FieldsController#update as JSON
I, [2019-04-18T16:16:10.169881 #18200]  INFO -- :   Parameters: {"field"=>{"type"=>"Fields::String", "name"=>"culture_in_AAT", "show_label"=>"Culture", "form_label"=>"Culture", "search_label"=>"Culture", "show_on_entity"=>true, "is_identifier"=>false}, "klass"=>"Fields::String", "kind_id"=>"3", "id"=>"105"}
I, [2019-04-18T16:16:10.177564 #18200]  INFO -- : Auth: user 'admin' has been seen
I, [2019-04-18T16:16:10.188199 #18200]  INFO -- :   Rendered fields/_customized.json.jbuilder (0.3ms)
I, [2019-04-18T16:16:10.188848 #18200]  INFO -- :   Rendered fields/save.json.jbuilder (1.3ms)
I, [2019-04-18T16:16:10.189161 #18200]  INFO -- : Completed 406 Not Acceptable in 19ms (Views: 2.1ms | ActiveRecord: 3.3ms)`

**Comment by Diederka** [comment]
Here the code in a file
[part_of_logfile.txt](https://github.com/coneda/kor/files/3094921/part_of_logfile.txt)

**Comment by moritzschepp** [comment]
Thanks, yes that's the right file and the right part of it: Essentially "Not Acceptable" is rendered when the data in some form is not complying with the validation rules. The field name "culture_in_AAT" has capital letters and is therefore refused. I wonder how you managed to create the field with this name, though: The form should have refused to save it. Did you add it manually via MySQL? If so, please make sure to rename it to a lower case name. The underscores are ok.

**Comment by Diederka** [comment]
OMG, i totally overlooked this, though I am using this system for nearly two years now. No capital letters, and no whitespaces, how could I forget? Sorry! Thanks!
