### ISSUE TITLE
editing a dataset field via backend

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#236]
I understood that editing fields of entities is not possible via ruby, just the creation is possible. 
is this correct? 
or is there a way to edit existing entities? 
for example: I would like to fill the new data set field of the entity type artefact. 
The field is called "culture", I want to fill it with the string "300017826" for EVERY Entity. 
Is this possible? 
(As i stated before. this field is only useful for third parties, which use our data. If someone there searches for Maya oder Mayan, they will find our stuff) Thus in the generator code I will to create the link mechanism wich leads to the Authority File (AAT Thesaurus) where the ID number 300017826 is resolved.

**Comment by Diederka** [comment]
PS: i forgot. maybe it is possible to edit the field via MySQL?

**Comment by moritzschepp** [comment]
You can for sure update entities with ruby, e.g.:

~~~ruby
entity = Entity.find(12345)
entity.dataset['culture'] = '300017826'
entity.save
~~~

However, if you just want to do that for the generator for ALL entities, then you can just hardcode the value in the generator directive. You don't need to refer to a field there.

**Comment by Diederka** [comment]
I need this only for the entity Type "Artefact". 
I think i can thus use the following code? 

```
entity = Kind.where(:name => 'Artefact').first
entity.dataset['culture'] = '300017826'
entity.save
```

**Comment by moritzschepp** [comment]
~~~ruby
entity = Kind.where(:name => 'Artefact').first
~~~
gives you a `kind`, so perhaps you want to
~~~ruby
kind = Kind.where(:name => 'Artefact').first
entity = kind.entities.find(12345)
...
~~~
instead.

**Comment by Diederka** [comment]
oh okay. but i don't have to search for something in the artefacts, so would it be enough to just write `entity = kind.entities` without something to find? So in the end the code would be: 
```ruby
kind = Kind.where(:name => 'Artefact').first
entity = kind.entities
entity.dataset['culture'] = '300017826'
entity.save
```

**Comment by moritzschepp** [comment]
you can either act on a single entity (e.g. the first) with:
~~~ruby
kind = Kind.where(:name => 'Artefact').first
entity = kind.entities.first
entity.dataset['culture'] = '300017826'
entity.save
~~~

or on all of them with a loop:
~~~ruby
kind = Kind.where(:name => 'Artefact').first
kind.entities.each do |entity|
   entity.dataset['culture'] = '300017826'
   entity.save
end
~~~

**Comment by Diederka** [comment]
Okay. Thanks! 
The mass edition worked fine.

**Comment by Diederka** [comment]
I also have to ask again here: If I will run the script again now to add the fields 'culture' to the hundreds of new entities, will the already existing values be acknowledged ? 
or will they duplicated - like what happened to relationships.datings? in my issue #248
 so can i prove if the field is empty in an if clause like 

   ruby ```` 
 if entity.dataset['culture'] == 0
````
or like 
   ruby ````
        if entity.dataset.where('culture').count == 0
    ````

**Comment by Diederka** [comment]
Okay thanks,!s
So I understand that dataset fields all have that key value pair (i remember in mysql these are paired as jason strings in an array) and thus they can't be created double.

**Comment by moritzschepp** [comment]
Yes, exactly!
