### ISSUE TITLE
How to get only Entities of a specific Entity Type (kind) via OAI-PMH? 

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#237]
I am trying to use some export OAI-datasets for trying to create my mapping to LIDO. But with the OAI-request for entities
https://classicmayan.kor.de.dariah.eu/api/oai-pmh/entities.xml?verb=ListRecords&metadataPrefix=kor 
I only get a certain number of entities (before the resumption token) and these are only Artefacts. 
I need to habe sets of the other 6 entity types (Medium, Holder, Collection, Person, Place, Provenance). 
How can I ask for some of these entities of a specific Entitiy Type? (just for havingdata  examples for my Mapping)
Which verb do I have to use? 
PS: The same question will I have for relationships of a specific relation.

**Comment by moritzschepp** [comment]
The OAI-PMH interface doesn't select by kind. The fact that you are seeing only "Artefacts" on `ListRecords` is coincidence. If you just need examples, you can use `GetRecord` with a UUID (shown on the entity page) as `identifier`.

**Comment by Diederka** [comment]
Super cool! Thanks! 
I did that! It worked! So I now have an example export for every Entity Type.
