### ISSUE TITLE
How to get only one specific Relationsips for every Relation via OAI-PMH? 

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#239]
I'm afraid I have to ask again. I think this issue is somehow related to the issue #237. 
There I learned to ask for entities via GetRecord using their ID (shown in the master data as UUID). 
How can I use OAI to query the individual relationships if I can't find any IDs for them in the masterdata in the browser? 
I would like to have one of the 17 possible ones in export...
Beyond that: 
The question is how the entities and relationships are connected. I reckon via IDs. But how do I get them? I ask because of my planned mapping of the data to DDB-LIDO. And the DDB employee already said that they expect an export in which everything is in a single file. 
How do I create such a file via OAI query?

**Comment by moritzschepp** [comment]
Nothing to be afraid of!

The main purpose of the OAI-PMH interface is to connect a "repository" (the ConedaKOR installation) to a "harvester" (in your case the DDB). The main use-case is the harvesting of **all** data in the repository. Filtering features are only in place to facilitate this use-case, e.g. to make the data quantity per request manageable. This is why the specification doesn't foresee semantic filters (like in this case to filter relationships by endpoint)

So for effectively transferring all the data while piping it through a mapping process, only the first part can be achieved with OAI-PMH. The second part has to be done with some other technology. In the past we did this by saving all XML files from OAI-PMH to files ([ConedaKOR includes a harvester](https://github.com/coneda/kor/blob/master/script/oai_pmh_client) which does exactly that) and then applying the mapping on them.

**Comment by Diederka** [comment]
Thank you very much, that answer makes things clearer.
