### ISSUE TITLE
searching dating or tags not possible for media. related with search issue #135

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#244]
I find it very useful that in version 4 the field "dating" for the medium is also visible in the relation to e.g. a work. So you can see at a glance when the different pictures of a work were taken (I missed this feature in version 3).
But I still have a problem with the missing searchability of media in version 4: 
Especially the fields "tags" and "dating" (which do not belong to the dataset) are searchable in all entities but not to the medium. But it would be immensely useful if they were transparent to the medium. 
Maybe I just don't know about it. But is there anything planned?

**Comment by Diederka** [comment]
Or do I misunderstand something? is there a way to automatically build a link via the ID (the UUID in the masterdata) to the respective entity? 
Or are these informations in the harvested data? 
As yo mentioned in #239, there is a way to harvest all data (which I haven't used yet): 

> So for effectively transferring all the data while piping it through a mapping process, only the first part can be achieved with OAI-PMH. The second part has to be done with some other technology. In the past we did this by saving all XML files from OAI-PMH to files ([ConedaKOR includes a harvester which does exactly that](https://github.com/coneda/kor/blob/master/script/oai_pmh_client)) and then applying the mapping on them.

>

**Comment by moritzschepp** [comment]
Can post a link where the medium datings are visible on a relation to a work?

We have a ticket for searching media (#135). Its somewhat old and until now its not assigned to a version. @wuebbena?

**Comment by moritzschepp** [comment]
I'm not sure I understand your last comment. There are 4 OAI-PMH interfaces, essentially. Have a look at https://github.com/coneda/kor#oai-pmh. They each allow the 6 OAI-PMH verbs `Identify`, `GetRecord`, `ListSets`, `ListRecords`, `GetRecord`, `ListIdentifiers` and `ListMetadataFormats`. The [specification](http://www.openarchives.org/OAI/openarchivesprotocol.html#ProtocolMessages) has examples for each of them and typical responses.

**Comment by Diederka** [comment]
Oh, sorry I don't know why I posted the last comment about OAI-PMH Question into the wrong thread.  I will remove it here.

**Comment by Diederka** [comment]
> I'm not sure I understand your last comment. There are 4 OAI-PMH interfaces, essentially. Have a look at https://github.com/coneda/kor#oai-pmh. They each allow the 6 OAI-PMH verbs `Identify`, `GetRecord`, `ListSets`, `ListRecords`, `GetRecord`, `ListIdentifiers` and `ListMetadataFormats`. The [specification](http://www.openarchives.org/OAI/openarchivesprotocol.html#ProtocolMessages) has examples for each of them and typical responses.

Oh, sorry I don't know why I posted the last comment about OAI-PMH Question into the wrong thread. I will remove it here.

**Comment by moritzschepp** [comment]
Oh ok, no problem.

**Comment by Diederka** [comment]
> Can post a link where the medium datings are visible on a relation to a work?
okay, 
in the screenshot we see the entity type work with the entity of a church and can see at a glance when the two different images (media) of the church were taken. the feature is not yet available in the current version 3.0.0, but it is very practical. Until now, you couldn't see the different creation dates of the medium directly when viewing a work. 
now there is only one wish left: :-) that is why i posted the issue: the feature of searching the datings (and tags) of media would be great. 
<img width="765" alt="Screenshot 2019-05-01 18 37 31" src="https://user-images.githubusercontent.com/25532142/57029378-d85a9580-6c41-11e9-938c-3adb035c4533.png">

**Comment by moritzschepp** [comment]
These datings are not pulled in from the image, they are entered with the relationship.

The features was added in v2.1.0. The usage here in this specific example is somewhat unclear. Imaging a teacher-pupil relationship between two people: `Karla - was teacher of -> Klaus`: You could now add the additional information `Karla - was teacher of (1899–1903) -> Klaus` . As you can see, this dating information wouldn't make any sense on `Karla` nor on `Klaus`.

For searching media, let's see what @wuebbena says.

**Comment by Diederka** [comment]
Oh now I found the feature, editing the relationship via additional properties or datings. 
We had none of this because we did a mass import of data and relations via ruby script ... and we worked hard on the scripts which sometimes still were not optimal. 
Hmmm, would there be a way to additionaly add them to every existing relationship via script? 
The relation would have to use the dating in every medium field.

**Comment by moritzschepp** [comment]
You mean to show the dating information from the medium on the work entity page?

**Comment by Diederka** [comment]
yes. 

our import script just filled the data fields, and relation fields, but nothing more. 
the dating fields from the excel colummn [3]. 
```ruby 
File.read("/home/kor/sourceFiles/source_import.csv").split("\n")[1..-1].each do |line|
  fields = line.split(";")

  if(File.file?("/home/kor/IMAGESinJPG/" + fields[1] + ".jpg"))
    width = Dimensions.width("/home/kor/IMAGESinJPG/" + fields[1] + ".jpg")
    height = Dimensions.height("/home/kor/IMAGESinJPG/" + fields[1] + ".jpg")
    end

  jsonData = "{\"image_no\" : \"" + fields[1] + "\",
(...) 
 jsonObj = JSON.parse(jsonData)
  puts jsonData
  if(File.file?("/home/kor/IMAGESinJPG/" + fields[1] + ".jpg"))    
    work = Entity.new(
      :kind => document,
      :medium => Medium.new(document: File.open("/home/kor/IMAGESinJPG/" + fields[1] + ".jpg")),
      :collection => default,
      :dataset => jsonObj,
      :distinct_name => fields[1],
      :datings => [
        EntityDating.new(label: "Year", dating_string: fields[3])
      ]
      )
   ````
how could the dat from colum 3 be used to be a daring information within the relation?

**Comment by Diederka** [comment]
another question: 
How can I create a ruby script to use the given keys (titles) and values in the datings of each medium to write them into their respective relation "medium depicts artefact"? That would be a big added value. 
Also I would write via script the respective collection names into the property fields of the relations. 
*another thing, but this is wishful thinking because it would be too difficult maybe to code it, would be to ask if there is a collection, and if not the place is filled and the artefact is "in situ". these information are only derivable and thus not obviosly visible at the moment.

**Comment by moritzschepp** [comment]
> how could the dat from colum 3 be used to be a daring information within the relation?

AFAIKS, you aren't creating any relationships in that code snippet. It depends how you created the relationships if you want to add dating information to them. I feel I have to warn you a bit: The relationship datings are probably not a good choice for the date when a picture was taken. The relationship datings apply to the relationship only, not the entity: If you were to relate the medium with another work, the relationship dating would only show on the first work entity.

If you still want to proceed, perhaps its easier to copy the dating information from the media to the relationships, e.g.

~~~ruby
Entity.media.all.each do |entity|
  value = entity.dataset['some_field']
  entity.outgoing_relationships.where(relation_name: 'zeigt').each do |dr|
    dr.relationship.datings << RelationshipDating.new(label: 'Datum', dating_string: value)
  end
end
~~~

Make sure to check the field names and have a backup ready before you run this.

**Comment by Diederka** [comment]
Sorry, I added the entity creation snippet, just for completeness, our relation code looked like so. 
```` ruby 
 default = Collection.where(:name => 'default').first
  artefact = Kind.where(:name => 'Artefact').first
  medium = Kind.where(:name => 'Medium').first

  relationship =
    medium.entities.each do |medium_entity|
      artefact.entities.where(:name => medium_entity.dataset['medium_depicts_artefact']).each do |artefact_entity|
        puts "SUCCESS"
        unless Relationship.related?(medium_entity, "medium depicts artefact", artefact_entity)
          Relationship.relate_and_save(medium_entity, "medium depicts artefact", artefact_entity)
        end
      end
    end
  puts "Finished medium_depicts_artefact"
`````
Okay, so if a have an image showing tw artefacts, the reltion dating only appears at the first artefact depicted? 
I didn't show the whole code of ceating our media. 
But luckily we have also always filled the date into a dataset field called date_time_created (because in the beginning we weren't so sure how the dating fields were to handle and what their purpose was 
```` ruby  
\"date_time_created\" : \"" + fields[3] + "\" 
```` ruby 
so I theoretically could copy the values from the dataset fields "date_time_created" to the relations too.

**Comment by moritzschepp** [comment]
I close this because the issues seems obsolete by now. Don't hesitate to reopen if you disagree.
