### ISSUE TITLE
Neither the Simple Search nor the Expert Search do work after setting up version 3.0.1	

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#247]
Since yesterday our kor database runs Version 3.0.1. 
[https://classicmayan.kor.de.dariah.eu/
](https://classicmayan.kor.de.dariah.eu/
)But since then unfortunalety the search is broken. 
Neither the Simple Search nor the Expert Search do work after setting up version 3.0.1	https://classicmayan.kor.de.dariah.eu/component_search
https://classicmayan.kor.de.dariah.eu/component_search

**Comment by Diederka** [comment]
Thanks for Fixing it so quickly!

**Comment by moritzschepp** [comment]
I'm afraid I had nothing to do with the fix.

Please be aware that we can't fix problems with your specific ConedaKOR installation. We don't have access to these systems.
