### ISSUE TITLE
how to delete datings or properties of built relationships

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#248]
i did a mass edition and put datings to relationships via ruby script. it worked out fine. 
I am content with the outcome. 
but somehow i run the script for a specific relation twice - and I did't know that a relationship can have 1-n datings filled. 
so now the dating of relationship "medium was created by person " is  filled double. 
It is a bit unpleasant. 

see example: 
https://classicmayan.kor.de.dariah.eu/blaze#/entities/11391

Question: 
how is it possible to delete only the datings or / and properties of a built relationship? 
maybe like so?
```` ruby
begin
  Kind.find_by(name: 'Medium').relationship.datings.where(relation_name: 'medium was created by person').each{|e| e.really_destroy!} 
end
```` 
FYI: 
afterwards I would like to just run the following script again:  (this script I made with your help and it works fine but maybe I should have used an "unless" condition or a "puts" output to control if already a value has been put in... )

```` ruby
KOR_ROOT="/home/kor/kor/"

# loading the rails environment
require "#{KOR_ROOT}/config/environment" 
Entity.media.all.each do |entity|
  value = entity.dataset['date_time_created']
  entity.outgoing_relationships.where(relation_name: 'medium was created by person').each do |dr|       
    dr.relationship.datings << RelationshipDating.new(label: 'Creation Date of Medium', dating_string: value)
  end
end
````

**Comment by Diederka** [comment]
Thanks, that looks good. I will try it out tomorrow 
when I also import new datasets.

**Comment by Diederka** [comment]
But a question, you are checking if a relation has already a value here: 
```` ruby
 if datings.where(label: 'Creation Date of Medium').count == 0
      datings << RelationshipDating.new(label: 'Creation Date of Medium', dating_string: value)
    end

 what if there was no dating value at the entity? 
I hope it won't copy an empty string to the relation with a label.

**Comment by Diederka** [comment]
Oh super, thanks! I will try itall out  today.

**Comment by Diederka** [comment]
I got it! 
I first create new dating values for the specific relationship and then I erase the ones which are double. It worked fine. 
First I had problems, because local variables were missing or were not "local" as i realized. but this code now works: 
```` ruby
KOR_ROOT="/home/kor/kor/"

# loading the rails environment
require "#{KOR_ROOT}/config/environment"
Entity.media.all.each do |entity|
  value = entity.dataset['date_time_created']
  entity.outgoing_relationships.where(relation_name: 'medium was created by person').each do |dr|
    datings = dr.relationship.datings

    # you can add new ones after checking a condition
    if datings.where(label: 'Creation Date of Medium').count == 0
      if value.present? # this checks for the empty string, only white-space, nil, 0 and so on
        dr.relationship.datings << RelationshipDating.new(label: 'Creation Date of Medium', dating_string: value)
      end

      # or remove all datings but the first
      if datings.where(label: 'Creation Date of Medium').count > 1
        to_be_removed = datings.where(label: 'Creation Date of Medium').to_a[1..-1] # array indices start at 0 and go to -1
        to_be_removed.each{|d| d.destroy}
      end
    end
  end
end
````

**Comment by moritzschepp** [comment]
Very good! I'm glad it worked.
