### ISSUE TITLE
VM credentials, install options, versions

### ISSUE THREAD

**Issue by nunulili** [coneda/kor#253]
Hi,
I found here the possibility how to import an OVA template into KVM:
https://blogs.oracle.com/oda/kvm-import-an-ova-template

Would like to know what the credentials for the VM is?

Thanks,
nunulili

**Comment by moritzschepp** [comment]
Hi @nunulili, thanks for sharing this!

The VM was priobably built with vagrant so it should allow login with user "vagrant" and password "vagrant". This user should allow passwordless `sudo -i`.

If I may ask, where did you download the ova file from?

**Comment by nunulili** [comment]
MANY THANKS!!!

> If I may ask, where did you download the ova file from?

I download the ova file (coneda-kor.v2.1.0.ova) from here: https://download.coneda.net/releases/

**Comment by moritzschepp** [comment]
Right, unfortunately, we stopped building the VMs at some point, mainly because they only served demo purposes but they didn't work well for production deployments. v2.1.0 is rather old, for more recent versions, please have a look at https://github.com/coneda/kor/releases

**Comment by nunulili** [comment]
Thanks for the tip. Can I just update the version 2.1.0 or do I have to install it again?

**Comment by moritzschepp** [comment]
You can do either but the processes are not well documented at the moment. We are working on easier deployment methods but for now, the best we have is install docs for the unreleased v4.0 at https://github.com/coneda/kor/blob/master/INSTALL.md I'm happy to help if you are running into issues.

**Comment by nunulili** [comment]
Then I will try it the next days and get back to you.
Thanks for the support !!!

**Comment by nunulili** [comment]
Can I install the whole synonymous on Ubuntu 16 server?

**Comment by moritzschepp** [comment]
In principle, you should be able to install it on any supported debian/ubuntu. Make sure to use a supported ruby version (>= 2.4). The install guide recommends rbenv because this allows the installation of multiple/non-apt ruby versions.

**Comment by nunulili** [comment]
Hi,

if I create the database with:

`RAILS_ENV=production bundle exec rake db:setup`

get the following error message:

```
Could not find rake-12.3.3 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by moritzschepp** [comment]
The suggested fix to run `bundle install` should work. If not, can you post the output?

**Comment by nunulili** [comment]
it works with sudo, but I get the following error message:

`DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from <top (required)> at /var/kor/app/config/application.rb:11)
rake aborted!
URI::InvalidURIError: the scheme mysql2 does not accept registry part: root:KUwi18 (or bad hostname?)
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:35:in `initialize'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:258:in `new'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:258:in `resolve_url_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:246:in `resolve_hash_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:221:in `resolve_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:138:in `resolve'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:150:in `block in resolve_all'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:149:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:149:in `resolve_all'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_handling.rb:73:in `resolve'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/core.rb:46:in `configurations='
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/core.rb:48:in `block in <module:Core>'
/var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/concern.rb:120:in `class_eval'
/var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/concern.rb:120:in `append_features'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/base.rb:290:in `include'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/base.rb:290:in `<class:Base>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/base.rb:274:in `<module:ActiveRecord>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/base.rb:24:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/mysql_database_tasks.rb:6:in `require'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/mysql_database_tasks.rb:6:in `<class:MySQLDatabaseTasks>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/mysql_database_tasks.rb:3:in `<module:Tasks>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/mysql_database_tasks.rb:2:in `<module:ActiveRecord>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/mysql_database_tasks.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:66:in `require'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:66:in `<module:DatabaseTasks>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:37:in `<module:Tasks>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:4:in `<module:ActiveRecord>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:3:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/railtie.rb:35:in `require'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/railtie.rb:35:in `block (3 levels) in <class:Railtie>'
/var/lib/gems/2.3.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config
(See full trace by running task with --trace)
`

**Comment by nunulili** [comment]
if I follow the instructions on the page of 
https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md  
then get the following error message:
`grep: **/*.rake: No such file or directory
sed: can't read s|FactoryGirl|FactoryBot|: No such file or directory`

**Comment by moritzschepp** [comment]
The factory_girl message is only a deprecation warning. You can safely ignore it. The actual problem is:

    URI::InvalidURIError: the scheme mysql2 does not accept registry part: root:KUwi18

Can you verify the configured mysql connection string (see .env.example for the format)? If you are using special characters, they need to be uri-escaped. Does that solve the problem?

**Comment by nunulili** [comment]
Thank you. But I have changed the root password to root and now get the following error message:

`DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from <top (required)> at /var/kor/app/config/application.rb:11)
rake aborted!
URI::InvalidURIError: the scheme mysql2 does not accept registry part: root:root:3306 (or bad hostname?)
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:35:in `initialize'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:258:in `new'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:258:in `resolve_url_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:246:in `resolve_hash_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:221:in `resolve_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:138:in `resolve'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:150:in `block in resolve_all'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:149:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/connection_specification.rb:149:in `resolve_all'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_handling.rb:73:in `resolve'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/core.rb:46:in `configurations='
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/core.rb:48:in `block in <module:Core>'
/var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/concern.rb:120:in `class_eval'
/var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/concern.rb:120:in `append_features'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/base.rb:290:in `include'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/base.rb:290:in `<class:Base>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/base.rb:274:in `<module:ActiveRecord>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/base.rb:24:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/mysql_database_tasks.rb:6:in `require'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/mysql_database_tasks.rb:6:in `<class:MySQLDatabaseTasks>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/mysql_database_tasks.rb:3:in `<module:Tasks>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/mysql_database_tasks.rb:2:in `<module:ActiveRecord>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/mysql_database_tasks.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:66:in `require'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:66:in `<module:DatabaseTasks>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:37:in `<module:Tasks>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:4:in `<module:ActiveRecord>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:3:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/railtie.rb:35:in `require'
/var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/railtie.rb:35:in `block (3 levels) in <class:Railtie>'
/var/lib/gems/2.3.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config
(See full trace by running task with --trace)
`

**Comment by nunulili** [comment]
When I call the page, you will see the following:  
https://d.pr/i/SEwkMb

**Comment by nunulili** [comment]
I turned on PassengerFriendlyErrorPages and get the following error messages:

`Web application could not be started
Permission denied @ rb_sysopen - /var/kor/data/settings.json.lock (Errno::EACCES)
  /var/kor/app/lib/kor/settings.rb:173:in `initialize'
  /var/kor/app/lib/kor/settings.rb:173:in `open'
  /var/kor/app/lib/kor/settings.rb:173:in `with_lock'
  /var/kor/app/lib/kor/settings.rb:71:in `load'
  /var/kor/app/lib/kor/settings.rb:10:in `initialize'
  /var/kor/app/lib/kor/settings.rb:15:in `new'
  /var/kor/app/lib/kor/settings.rb:15:in `instance'
  /var/kor/app/lib/kor.rb:3:in `settings'
  /var/kor/app/app/mailers/user_mailer.rb:2:in `<class:UserMailer>'
  /var/kor/app/app/mailers/user_mailer.rb:1:in `<top (required)>'
  /var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
  /var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
  /var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
  /var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
  /var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:380:in `block in require_or_load'
  /var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
  /var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
  /var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
  /var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:37:in `load_interlock'
  /var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:358:in `require_or_load'
  /var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:336:in `depend_on'
  /var/lib/gems/2.3.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:252:in `require_dependency'
  /var/lib/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
  /var/lib/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/engine.rb:475:in `each'
  /var/lib/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/engine.rb:475:in `block in eager_load!'
  /var/lib/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/engine.rb:473:in `each'
  /var/lib/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/engine.rb:473:in `eager_load!'
  /var/lib/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/engine.rb:354:in `eager_load!'
  /var/lib/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/application/finisher.rb:59:in `each'
  /var/lib/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
  /var/lib/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/initializable.rb:30:in `instance_exec'
  /var/lib/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/initializable.rb:30:in `run'
  /var/lib/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /var/lib/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/initializable.rb:54:in `run_initializers'
  /var/lib/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/application.rb:352:in `initialize!'
  /var/kor/app/config/environment.rb:5:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
  /var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
`Error ID
21be878b
Application root
/var/kor/app
Environment (value of RAILS_ENV, RACK_ENV, WSGI_ENV, NODE_ENV and PASSENGER_APP_ENV)
production
Ruby interpreter command
/home/app/.rbenv/shims/ruby
User and groups
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)`


I left out the rest 
![image](https://user-images.githubusercontent.com/54329643/63647900-3434b700-c728-11e9-8f85-4b75ee1ad36b.png)

**Comment by moritzschepp** [comment]
If you are using passenger, the app will be started with the user/group the `config.ru` file belongs to. If it belongs to root, the app will be started with user `nobody`. Whichever user applies, you have to grant rw access to the data dir (`/var/kor/data` in your case). Does that fix the error?

BTW, the application should log to `log/production.log`.

**Comment by nunulili** [comment]
Now I don't get an error message anymore but nothing is displayed. Just a blank page.
And the file production.log is empty and without content

**Comment by nunulili** [comment]
Thanks alot. Everything works fine now. Thanks again for the great support !!!

**Comment by nunulili** [comment]
Hi,

I have still one question!
Can and do I have to install the Elasticsearch after installing ConedaKOR?

Thanks,
nunulili

**Comment by nunulili** [comment]
I have now installed elasticsearch and created an index with the following command and otherwise I didn't changed nothing in setting: "/etc/elasticsearch/elasticsearch.yml":

`curl -XPUT 'localhost: 9200 / kor? pretty'`

And in .env I have now the following entry:

```
ELASTIC_URL="http://localhost:9200"
ELASTIC_INDEX="kor"
```

With the command bundle exec bin/kor index-all get the following error message:

```
bundler: failed to load command: bin/kor (bin/kor)
Mysql2::Error: Access denied for user 'root'@'localhost' (using password: YES)
  /var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `connect'
  /var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `initialize'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/connection_handling.rb:91:in `connection'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/model_schema.rb:462:in `load_schema!'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/attributes.rb:233:in `load_schema!'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/attribute_decorators.rb:28:in `load_schema!'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/model_schema.rb:455:in `block in load_schema'
  /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/model_schema.rb:452:in `load_schema'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/model_schema.rb:348:in `columns'
  /var/lib/gems/2.3.0/gems/acts-as-taggable-on-4.0.0/lib/acts_as_taggable_on/taggable/cache.rb:37:in `columns'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/model_schema.rb:389:in `column_names'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/relation/calculations.rb:214:in `aggregate_column'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/relation/calculations.rb:237:in `execute_simple_calculation'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/relation/calculations.rb:207:in `perform_calculation'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/relation/calculations.rb:121:in `calculate'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/relation/calculations.rb:40:in `count'
  /var/lib/gems/2.3.0/gems/activerecord-5.0.7.2/lib/active_record/querying.rb:13:in `count'
  /var/kor/app/lib/kor/elastic.rb:184:in `index_all'
  /var/kor/app/lib/kor/tasks.rb:24:in `index_all'
  /var/kor/app/lib/kor/command_line.rb:88:in `task'
  /var/kor/app/lib/kor/command_line.rb:115:in `run'
  bin/kor:11:in `<top (required)>'
```

 but with this command it seems to work:
 `RAILS_ENV=production bundle exec bin/kor index-all`

Is this all so OK or do I have to do something else? And should I also install neo4j too?

**Comment by moritzschepp** [comment]
Yes exactly, `RAILS_ENV=production` sets the environment (think mode) in which the app is running, there is `development` for coding on a workstation, `test` for automated tests and `production` for actual deployments.

I don't think you need to do anything else. neo4j is entirely optional: once you have some data, you can install it and export to it to query your data with CYPHER.

**Comment by nunulili** [comment]
That means I should not change or comment out anything in the file "/etc/elasticsearch/elasticsearch.yml"?
And should I write for ELASTIC_URL rather "http://localhost:9200" or "http://127.0.0.1:9200"?

And thank you again for the great support.

**Comment by moritzschepp** [comment]
Oh I see what you mean. The configuration of elasticsearch depends a lot on your specific server landscape. If you just use it for kor, the defaults in elasticsearch.yml should be fine.

Its not like with MySQL that "localhost" would make the client connect via a socket while 127.0.0.1 would use the network stack. To my knowledge both urls are interchangeable.

**Comment by nunulili** [comment]
Why I asked, because all the settings in elasticsearch.yml are commented out!

```
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
#cluster.name: my-application
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
#path.data: /path/to/data
#
# Path to log files:
#
#path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 192.168.0.1
#
# Set a custom port for HTTP:
#
#http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes: 3
#
# For more information, consult the zen discovery module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
```

**Comment by moritzschepp** [comment]
That's just their way of showing you a bit of documentation for the config values.
