### ISSUE TITLE
Write installer to allow basic configuration via web interface

### ISSUE THREAD

**Issue by moritzschepp** [coneda/kor#26]
This could be done by modifying config.ru à la:

```
setup = Proc.new do |env|
  [200, {'content-type' => 'text/html'}, ["setup"]]
end

wrapper = Proc.new do |env|
  if File.exists?("#{RAILS_ROOT}/config/database.yml")
    unless defined?(Kor::Application)
      require "#{RAILS_ROOT}/config/environment"
    end
    Kor::Application.call(env)
  else
    setup.call(env)
  end
end

run wrapper
```

**Comment by moritzschepp** [comment]
I think this ticket can be closed because we have the .env Files in v4.0 and the amount of config values are reduced to 4. When KOR is installed, the admin has to install some things on the command line anyhow, so I don't think that an installer vor those 4 configs would help a lot. @wuebbena, what do you think? The install manual describes the entire procedure at https://github.com/coneda/kor/blob/v4.0/INSTALL.md

**Comment by wuebbena** [comment]
Yeah, I agree with you on that.

**Comment by moritzschepp** [comment]
That was easy!
