### ISSUE TITLE
entity validation errors when working with Frankfurt database

### ISSUE THREAD

**Issue by S-Peter** [coneda/kor#27]
* there are entity datasets in the Frankfurt database that are not valid according to the current validation criteria. Errors are mostly due to already taken names or invalid distinct_names, but not exclusively. If you need more detailed information let me know. I logged the errors and corresponding entities.
* consecutive spaces in name and distinct_name fields are already taken care of; these validation errors do not appear in my logged errors file

**Comment by moritzschepp** [comment]
Could you write a failing test for this?

**Comment by moritzschepp** [comment]
Is this still an issue?
