### ISSUE TITLE
Problems with the search

### ISSUE THREAD

**Issue by wuebbena** [coneda/kor#270]
The search does not work correctly in 4.0.1-pre. The search results have no relation to the query.
<img width="1363" alt="Bildschirmfoto 2020-01-15 um 21 57 02" src="https://user-images.githubusercontent.com/7914234/72478387-3213e780-37f2-11ea-8ed9-508fab8a1097.png">

**Comment by moritzschepp** [comment]
Turned out to be a data problem in the specific installation, closing.
