### ISSUE TITLE
"Primary Relation" and "Secondary Relation"

### ISSUE THREAD

**Issue by wuebbena** [coneda/kor#281]
The selection of "Primary Relation" and "Secondary Relation" is obviously saved, but has no effect.

**Comment by wuebbena** [comment]
After calling up the settings again, the selection is no longer displayed and now it does not work again.

**Comment by fabiancremer** [comment]
works for me

**Comment by fabiancremer** [comment]
and works no more

**Comment by moritzschepp** [comment]
Can you be more specific?
