### ISSUE TITLE
are all entity records provided?

### ISSUE THREAD

**Issue by S-Peter** [coneda/kor#29]
* I harvest only 129494 (+290 invalid) entity records of 261504 (Frankfurt database)
* in particular I don't harvest any medium entities (130906 of 261504)
* are all medium entities provided via ListRecords of entity repo? There are 130906 medium entities and 814 non-medium entities missing.

* with a smaller database (easydb dfk database) all records are harvested as expected.

* Do you have an idea why the harvest from the big database is incomplete?

**Comment by moritzschepp** [comment]
The endpoints provide all entiites the current user is authorized to see. If you don't specify an `api_key`, the current user is "guest". Also, be aware that the "admin" user doesn't necessarily have access to every collection, he is not automatically assigned to all user groups.
