### ISSUE TITLE
sendmail error User unknown

### ISSUE THREAD

**Issue by CrazyCrud** [coneda/kor#312]
First of all, thank you for the consistent work on kor.

I create new users in the administration. For this reason, emails with the password are sent to the newly registered users.
However, the emails are not sent. The user _admin@example.com_ is not known (obviously), unfortunately I do not know where to set the sender except in the `.env` file, which looks like this.   
```
MAIL_DELIVERY_METHOD="sendmail"

# Specifiy sendmail options
MAIL_SENDMAIL_LOCATION="/usr/sbin/sendmail"
MAIL_SENDMAIL_ARGUMENTS="-i -t"

NOTIFY_SENDER="name@domain.de"
```   
I set NOTIFY_SENDER to name@domain.de, so I don't really know where the _admin@example.com_ comes from.    

Here is the sendmail log:
```
Authentication-Warning: kor set sender to admin@example.com using -f
Jan 28 16:22:49 sendmail[4020]: 10SGMnGZ004020: from=admin@example.com, size=575, class=0, nrcpts=1, msgid=<6012e4d9909f0_e392b05bc72ed8055617@server.mail>, relay=kor@localhost
Jan 28 16:22:49 sm-mta[4021]: 10SGMnU7004021: from=<admin@example.com>, size=841, class=0, nrcpts=1, msgid=<6012e4d9909f0_e392b05bc72ed8055617@server.mail>, proto=ESMTP, daemon=MTA-v4, relay=localhost.localdomain [127.0.0.1]
Jan 28 16:22:49 sendmail[4020]: 10SGMnGZ004020: to=another.name@domain.de, ctladdr=admin@example.com (23642/23642), delay=00:00:00, xdelay=00:00:00, mailer=relay, pri=30575, relay=[127.0.0.1] [127.0.0.1], dsn=2.0.0, stat=Sent (10SGMnU7004021 Messa$
Jan 28 16:22:49 sm-mta[4023]: STARTTLS=client, version=TLSv1.2, verify=FAIL, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256/256
Jan 28 16:22:49 sm-mta[4023]: 10SGMnU7004021: to=<another.name@domain.de>, delay=00:00:00, xdelay=00:00:00, mailer=esmtp, pri=120841, dsn=5.7.27, stat=User unknown
Jan 28 16:22:49 sm-mta[4023]: 10SGMnU7004021: 10SGMnU7004023: DSN: User unknown
```

Otherwise, emails are sent successfully from the terminal to _another.name@domain.de_ via sendmail.   

Thank you in advance!

**Comment by moritzschepp** [comment]
Hey :)

The sender is simply the maintainer mail address: Log in with admin rights, then click on `Settings`, change the `Maintainer email address` and save. The effect should be immediate.

Let me know if it doesn't work.

**Comment by moritzschepp** [comment]
Oh and the `NOTIFY_SENDER` is only for exception notification mails. They contain debug information and the system sends them when a 500 is returned.

**Comment by CrazyCrud** [comment]
@moritzschepp thank you for the quick reply.
After changing the email in the administration and restarting apache, it works wonderfully.   
Users can now log in, however there seems to be a problem with the legal notice. After logging in you can not accept it and the page is then also no longer accessible. Only if you delete the cookies, you can get back to the page. Then you are asked again if you accept the legal notice. The legal notice is currently the default text.   

Here is the output of the browser console:   
![Screenshot from 2021-01-29 10-45-43-edit](https://user-images.githubusercontent.com/2430008/106261729-41f64200-6222-11eb-8814-40631a8ab209.png)
This is the screen the newly logged in user sees:
![Screenshot from 2021-01-29 10-46-01](https://user-images.githubusercontent.com/2430008/106261427-d90eca00-6221-11eb-809b-ca254607bfac.png)
And here is the production log:   
```
I, [2021-01-29T09:44:54.892989 #11100]  INFO -- : [d797ba08-7cc3-4b1d-b4f1-70981fa2eb41] Processing by UsersController#me as JSON
I, [2021-01-29T09:44:54.893054 #11100]  INFO -- : [d797ba08-7cc3-4b1d-b4f1-70981fa2eb41]   Parameters: {"include"=>"security"}
D, [2021-01-29T09:44:54.894740 #11100] DEBUG -- : [d797ba08-7cc3-4b1d-b4f1-70981fa2eb41]   User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 9 LIMIT 1
D, [2021-01-29T09:44:54.895854 #11100] DEBUG -- : [d797ba08-7cc3-4b1d-b4f1-70981fa2eb41]   HABTM_Groups Load (0.2ms)  SELECT `credentials_users`.* FROM `credentials_users` WHERE `credentials_users`.`user_id` = 9
I, [2021-01-29T09:44:54.896731 #11100]  INFO -- : [d797ba08-7cc3-4b1d-b4f1-70981fa2eb41] Redirected to 
I, [2021-01-29T09:44:54.896891 #11100]  INFO -- : [d797ba08-7cc3-4b1d-b4f1-70981fa2eb41] Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.6ms)
F, [2021-01-29T09:44:54.897513 #11100] FATAL -- : [d797ba08-7cc3-4b1d-b4f1-70981fa2eb41]   
F, [2021-01-29T09:44:54.897560 #11100] FATAL -- : [d797ba08-7cc3-4b1d-b4f1-70981fa2eb41] ActionController::UrlGenerationError (No route matches {:action=>"legal", :controller=>"static", :format=>"json"}):
F, [2021-01-29T09:44:54.897602 #11100] FATAL -- : [d797ba08-7cc3-4b1d-b4f1-70981fa2eb41]   
F, [2021-01-29T09:44:54.897666 #11100] FATAL -- : [d797ba08-7cc3-4b1d-b4f1-70981fa2eb41] app/controllers/json_controller.rb:129:in `legal'
```   

Sorry for the inconvenience and thank you again for your help.

**Comment by moritzschepp** [comment]
Its no inconvenience at all!

It seems to be a bug, I'll look into it. Which KOR version are you using?

**Comment by CrazyCrud** [comment]
@moritzschepp thank you.

The version according to `version.txt` is 4.0.0

**Comment by moritzschepp** [comment]
Very good, thanks.

There is a good chance you are seeing the same problem as in #258. That will be in 4.0.1. I'll fix the last issue in that version and then release it shortly.

**Comment by CrazyCrud** [comment]
Thank you very much!

**Comment by moritzschepp** [comment]
v4.0.1 is released. Does the new version fix your problem?

**Comment by CrazyCrud** [comment]
After the update the terms can be accepted and the user can browse the site without any problems.   
Thank you your support and the update.

**Comment by moritzschepp** [comment]
Excellent, I'm glad it worked. Thanks for the detailed bug report.
