### ISSUE TITLE
Failure in REST JSON API

### ISSUE THREAD

**Issue by MaximilianBrodhun** [coneda/kor#318]
The usage of the API is not working correct anymore.

REST API entities.josn?terms=*  doesn't show results and answers with: 

```
{"status":500,"error":"Internal Server Error"}
```

with kind_id=3 there is no problem.

Is this porblem beloging to our endpoint or is this a general problem?

**Comment by moritzschepp** [comment]
The error will probably go away when the Elasticsearch on the kor host is upgraded to v5 but in the meantime you should surely not get a 500. I'll look into it.

**Comment by moritzschepp** [comment]
Alright, the 500 is fixed so the message should be more meaningful now. I'm closing here but I'll let you guys know when elasticsearch is updated on the host.
