### ISSUE TITLE
Add easy editor for relationships

### ISSUE THREAD

**Issue by moritzschepp** [coneda/kor#32]
Now, the workflow is to "mark" an entity, then navigate to another and then create the link between them. This should be done by an inline editor on the entity page.

**Comment by moritzschepp** [comment]
Implementation is done

**Comment by wuebbena** [comment]
Wow! It works very smooth and helps so much. Thumbs up!

**Comment by moritzschepp** [comment]
Closing this ... we'll handle problems and additions within other issues.
