### ISSUE TITLE
changes in JSON-API?

### ISSUE THREAD

**Issue by MaximilianBrodhun** [coneda/kor#324]
Did you made changes in JSON-API?

In the response for GET\entities.json?terms there was a field "ids" did you delete that from the response?

Cheers

**Comment by moritzschepp** [comment]
Yes, we changed that, (see also https://github.com/coneda/kor/blob/v4.1/app/controllers/entities_controller.rb#L26). The parameter is called just `id` now.

**Comment by MaximilianBrodhun** [comment]
But is it the same?
Before there was a list of all ids from the response in one field.

And another question:

The response for:

```
https://classicmayan.kor.de.dariah.eu/relationships.json?entity_id=18322&relation_name=artefact%20is%20depicted%20by%20medium
```

and

```
https://classicmayan.kor.de.dariah.eu/relationships.json?entity_id=220&relation_name=artefact%20is%20depicted%20by%20medium
```

and it seems that th entity_id is not playing any role because also the response for a not given entity_id is the same:

```
https://classicmayan.kor.de.dariah.eu/relationships.json?entity_id=99999999999999999&relation_name=artefact%20is%20depicted%20by%20medium
```

Did you also change something regarding to this?

**Comment by moritzschepp** [comment]
Yes, like this:
https://classicmayan.kor.de.dariah.eu/entities.json?id=2,11388

Th relationship endpoint now allows filtering both sides of the relationship, therefore `entity_id` changed to `from_entity_id` or `to_entity_id`. There is also some documentation on this [here](https://github.com/coneda/kor/tree/v4.1#rest-json).

Is that what you need?

**Comment by MaximilianBrodhun** [comment]
No, unfortunately not.
I will take a look into the new API and change all the function I implemented.

I implemented a function to get from artefacts search by entitites.json?terms=... and kind_id=3. For those I take for each ID from the result, again the ID to get the related media. But I think I will find a new way to get the same result as before.

Hopefully I can transfer the same solution to the functions.

Cheers,

Max


----
Maximilian Brodhun
Abteilung Forschung & Entwicklung
Gruppe Kompetenzzentrum Forschungsdaten und Langzeitarchivierung

Georg-August-Universität Göttingen
Niedersächsische Staats- und Universitätsbibliothek Göttingen
D-37070 Göttingen

Papendiek 14 (Historisches Gebäude, Raum 2.409)
+49 551 39-27805 (Tel)
+49 551 39-3856 (Fax)


***@***.******@***.***>
http://www.sub.uni-goettingen.de
http://www.rdd.sub.uni-goettingen.de
________________________________
Von: Moritz Schepp ***@***.***>
Gesendet: Mittwoch, 17. März 2021 22:34:25
An: coneda/kor
Cc: Behnert-Brodhun, Maximilian; Author
Betreff: Re: [coneda/kor] changes in JSON-API? (#324)


Yes, like this:
https://classicmayan.kor.de.dariah.eu/entities.json?id=2,11388

Th relationship endpoint now allows filtering both sides of the relationship, therefore entity_id changed to from_entity_id or to_entity_id. There is also some documentation on this here<https://github.com/coneda/kor/tree/v4.1#rest-json>.

Is that what you need?

**Comment by moritzschepp** [comment]
You can also do
https://classicmayan.kor.de.dariah.eu/entities.json?terms=jones&include=related&related_kind_id=1

perhaps that helps?

**Comment by MaximilianBrodhun** [comment]
Thanks for that but unfortunately it doesn't help because it is necessary to serch at first in artefacts (kind_id=3) and from that results the linked media.

At frist we search media:

https://classicmayan.kor.de.dariah.eu/entities.json?terms=tikal%20altar&kind_id=3&per_page=15&page=1

Then I take the IDs of each object stores it an array.

For each of those IDs:

https://classicmayan.kor.de.dariah.eu/relationships.json?entity_id=220&relation_name=artefact%20is%20depicted%20by%20medium

To get the lDs of the linked media.

And in the last step:

https://classicmayan.kor.de.dariah.eu/entities/11383.json

To get the concrete data about the medium.

Works fine but now the result of the second request is everytime the same, so my self build json file has for every found object in the first request the same linked data.

Before the update it was fine but I have to figure out how to do it with the new api functions.

Cheers,

Max

----
Maximilian Brodhun
Abteilung Forschung & Entwicklung
Gruppe Kompetenzzentrum Forschungsdaten und Langzeitarchivierung

Georg-August-Universität Göttingen
Niedersächsische Staats- und Universitätsbibliothek Göttingen
D-37070 Göttingen

Papendiek 14 (Historisches Gebäude, Raum 2.409)
+49 551 39-27805 (Tel)
+49 551 39-3856 (Fax)


***@***.******@***.***>
http://www.sub.uni-goettingen.de
http://www.rdd.sub.uni-goettingen.de
________________________________
Von: Moritz Schepp ***@***.***>
Gesendet: Donnerstag, 18. März 2021 01:49:29
An: coneda/kor
Cc: Behnert-Brodhun, Maximilian; Author
Betreff: Re: [coneda/kor] changes in JSON-API? (#324)


You can also do
https://classicmayan.kor.de.dariah.eu/entities.json?terms=jones&include=related&related_kind_id=1

perhaps that helps?

**Comment by MaximilianBrodhun** [comment]
Hi again,

I found it and solved the problem.
Many thanks for your help!

Cheers

Max


----
Maximilian Brodhun
Abteilung Forschung & Entwicklung
Gruppe Kompetenzzentrum Forschungsdaten und Langzeitarchivierung

Georg-August-Universität Göttingen
Niedersächsische Staats- und Universitätsbibliothek Göttingen
D-37070 Göttingen

Papendiek 14 (Historisches Gebäude, Raum 2.409)
+49 551 39-27805 (Tel)
+49 551 39-3856 (Fax)


***@***.******@***.***>
http://www.sub.uni-goettingen.de
http://www.rdd.sub.uni-goettingen.de
________________________________
Von: Behnert-Brodhun, Maximilian
Gesendet: Donnerstag, 18. März 2021 10:55:06
An: coneda/kor; coneda/kor
Cc: Author
Betreff: AW: [coneda/kor] changes in JSON-API? (#324)


Thanks for that but unfortunately it doesn't help because it is necessary to serch at first in artefacts (kind_id=3) and from that results the linked media.

At frist we search media:

https://classicmayan.kor.de.dariah.eu/entities.json?terms=tikal%20altar&kind_id=3&per_page=15&page=1

Then I take the IDs of each object stores it an array.

For each of those IDs:

https://classicmayan.kor.de.dariah.eu/relationships.json?entity_id=220&relation_name=artefact%20is%20depicted%20by%20medium

To get the lDs of the linked media.

And in the last step:

https://classicmayan.kor.de.dariah.eu/entities/11383.json

To get the concrete data about the medium.

Works fine but now the result of the second request is everytime the same, so my self build json file has for every found object in the first request the same linked data.

Before the update it was fine but I have to figure out how to do it with the new api functions.

Cheers,

Max

----
Maximilian Brodhun
Abteilung Forschung & Entwicklung
Gruppe Kompetenzzentrum Forschungsdaten und Langzeitarchivierung

Georg-August-Universität Göttingen
Niedersächsische Staats- und Universitätsbibliothek Göttingen
D-37070 Göttingen

Papendiek 14 (Historisches Gebäude, Raum 2.409)
+49 551 39-27805 (Tel)
+49 551 39-3856 (Fax)


***@***.******@***.***>
http://www.sub.uni-goettingen.de
http://www.rdd.sub.uni-goettingen.de
________________________________
Von: Moritz Schepp ***@***.***>
Gesendet: Donnerstag, 18. März 2021 01:49:29
An: coneda/kor
Cc: Behnert-Brodhun, Maximilian; Author
Betreff: Re: [coneda/kor] changes in JSON-API? (#324)


You can also do
https://classicmayan.kor.de.dariah.eu/entities.json?terms=jones&include=related&related_kind_id=1

perhaps that helps?
