### ISSUE TITLE
Generator does not do what it should

### ISSUE THREAD

**Issue by wuebbena** [coneda/kor#327]
version 4.2.0-pre 

For the entity type "person", the field “wikidata_id” was created first. The transfer of the IDs from Wikidata into this field works without any problems. Afterwards, a generator was created to display a visible link to Wikidata from the IDs on the corresponding entity page. The default from the documentation was used for this: https://github.com/coneda/kor_leitfaden_ffm/wiki#generatoren-definieren [“[Ab Version 4.0] gilt hierfür folgendes Format:”]
A link is then created, but a Wikidata error page is displayed: “The requested page title contains invalid characters: "{". Return to Wikidata:Main Page.”

**Comment by moritzschepp** [comment]
The old syntax for generator directives has been replaced. Please see [the changelog for v4.0.1](https://github.com/coneda/kor/blob/master/CHANGELOG.md#version-401) for the new syntax.

**Comment by wuebbena** [comment]
Great, thanks for the quick help! 
Just for the record, in my case – the link via the ID to Wikidata – it will look like this:

```
<% if (entity.dataset.wikidata_id) { %>
   <a href="https://www.wikidata.org/wiki/<%= entity.dataset.wikidata_id %>" target="_blank">» Wikidata</a>
<% } %>
```

I'll also add this to the [manual](https://github.com/coneda/kor_leitfaden_ffm/wiki#generatoren-definieren).
