### ISSUE TITLE
Link to global group in master data is not given any more in version (version 4.1.0-pre)

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#351]
I happened to recognize that the link to the respective global group of an entity in its master data section is gone. (kor version 4.1.0-pre) 
And right now the global group is listed as before but without link. 
Is there a plan to bring the links, which are very handy, back?

**Comment by moritzschepp** [comment]
Yes absolutely, the links should be there!

I'll look into it.

**Comment by moritzschepp** [comment]
I added the links again. Do you like the format?

**Comment by Diederka** [comment]
Thanks! That's perfect. 
Now every directory in the hierarchy is also clickable (eg: Maya Image Archive -> Karl Herbert Mayer Archive). 
I like it.
