### ISSUE TITLE
JSON-API and technical metadata

### ISSUE THREAD

**Issue by MaximilianBrodhun** [coneda/kor#352]
In the documentation you pointed out that it is possible to get the technical metadata. 

But they won't be returned.

```
https://classicmayan.kor.de.dariah.eu/entities/11810.json?include=technical
```

Ignore the "include=technical".

I need metadata of the creation and change date of the digital file.

**Comment by moritzschepp** [comment]
Yes, you've got the right url but the "technical" data is subject to the "master data" authorization. If you'd like to give access to this for unauthenticated api calls, you'd make sure that account `guest`' is in a group that is listed the `Allow these groups to display the master data` permission on collection `Guest Collection`.

Keep in mind, that the "technical" data contains timestamps for the creation and modification of the entity, not for the uploaded file.

**Comment by moritzschepp** [comment]
I'll close this, don't hesitate to reopen if this doesn't resolve the issue.

**Comment by MaximilianBrodhun** [comment]
Thanks for this information. Works fine
