### ISSUE TITLE
Image Upload via browser doen not work at the moment (version 4.1.0-pre)

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#354]
I tried to upload an image (jpg) via Browser as usual. But it throws an error. 
our software has version 4.1.0-pre 
[https://classicmayan.kor.de.dariah.eu/](url)

Can you help me out
<img width="1005" alt="Bildschirmfoto 2021-11-04 um 12 32 23" src="https://user-images.githubusercontent.com/25532142/140308398-276d2346-c083-4734-b1e0-a0ae99f6ca8d.png">
?

**Comment by moritzschepp** [comment]
Yes, I think so: its a feature, not a bug :)

On the left you see all the mandatory fields. Does the upload work if you provide a value for all of them?

**Comment by Diederka** [comment]
ooooh, I had to fill in the fields BEFORE uploading? I didn't know that. 
That's when you don't work too often as data editor on your own database. 
Okay, thanks  :-)
