### ISSUE TITLE
Entity type not considered in new inline relationship functionality

### ISSUE THREAD

**Issue by bitno** [coneda/kor#41]
starting point: The user is on a specific entity and is trying to add a new relationship with the new functionality in v2.0. 
steps taken: The user selects a possible relationship from the dropdown menu and starts typing the target entity. Results are being shown.
problem: The results displayed don't take into account the possible target entity types. Although each relationship has clearly defined entity types on both ends.

**Comment by moritzschepp** [comment]
Right, thanks for reporting this.

**Comment by moritzschepp** [comment]
This is now implemented. Please have a look.

**Comment by bitno** [comment]
initial testing was a success, thank you @moritzschepp
