### ISSUE TITLE
new relationship functionality lets the user create impossible relationships

### ISSUE THREAD

**Issue by bitno** [coneda/kor#43]
starting point: The user is on a specific entity and is trying to add a new relationship with the new functionality in v2.0. 
steps taken: The user selects a possible relationship from the dropdown menu, selects a target entity and adds the relation.
problem: The relation is accepted, even of the relationship type is not meant for the two entity types used. 
example from the screenshot: person is being connected to a city with relation "wird dargestellt von". 
![bildschirmfoto 2016-02-25 um 16 59 34](https://cloud.githubusercontent.com/assets/15378927/13325376/d972e100-dbe1-11e5-85a8-d025b8a8c0db.png)

**Comment by moritzschepp** [comment]
I see your point. However, ensuring correct relations between specific entity types was always just a UI functionality. We don't actually validate this on the server ... and for now, this is a good thing: When you change a relation to allow other entity types, this doesn't correct existing relationships yet. So server validation would wrongly invoke confidence in the stored data. Once relationships are aligned with changes to relations retrospectively, we could also enforce validation on relationships.

That said, we should still implement this as a UI feature (already now)! But isn't that automatically implemented when #41 and #42 are done?

**Comment by bitno** [comment]
You are correct. Issues #41 and #42 would reduce the combinations to the possible ones and this would automatically make this issue obsolete. Thank you for pointing that out and also explaining, that the validation had even previously been done on the ui.
