### ISSUE TITLE
The actual entity is not visible in the section „session“.

### ISSUE THREAD

**Issue by wuebbena** [coneda/kor#44]
<img width="905" alt="bildschirmfoto 2016-02-26 um 14 36 28" src="https://cloud.githubusercontent.com/assets/7914234/13353642/16f8c666-dc96-11e5-9f30-ff582336d240.png">

**Comment by bitno** [comment]
I was able to reproduce that issue with an entity type "Medium", but it worked as expected with an entity type "Werk".
![bildschirmfoto 2016-02-26 um 16 57 07](https://cloud.githubusercontent.com/assets/15378927/13357362/2590e820-dcaa-11e5-98e6-847dc6556a17.png)

**Comment by moritzschepp** [comment]
Yes I know, I found the problem.

**Comment by moritzschepp** [comment]
It's fixed.

**Comment by wuebbena** [comment]
It works but it looks a little bit croped/clinched in comparison with the instance which is running in Frankfurt.

<img width="480" alt="bildschirmfoto 2016-02-29 um 17 47 27" src="https://cloud.githubusercontent.com/assets/7914234/13401378/27009d04-df0c-11e5-8989-dd9b66191e77.png">
<img width="374" alt="bildschirmfoto 2016-02-29 um 17 47 51" src="https://cloud.githubusercontent.com/assets/7914234/13401379/27016504-df0c-11e5-835c-9bd712a04191.png">

**Comment by moritzschepp** [comment]
I fixed an issue where media didn't show up properly within the session panel when recently added, a page reload had to be done to see them. Does this fix the problem you describe as well by any change? I can't reproduce the screenshot you posted.

**Comment by wuebbena** [comment]
Yes it does!
<img width="458" alt="bildschirmfoto 2016-03-01 um 00 37 33" src="https://cloud.githubusercontent.com/assets/7914234/13412694/4f034bc4-df45-11e5-922f-9dc86eec393d.png">
