### ISSUE TITLE
In „new entries“ a (work-)title is displayed above a medium 

### ISSUE THREAD

**Issue by wuebbena** [coneda/kor#45]
a) Why?
b) It isn't linked

<img width="300" alt="bildschirmfoto 2016-02-26 um 14 41 56" src="https://cloud.githubusercontent.com/assets/7914234/13353795/01ca3a4e-dc97-11e5-9e19-562cd3aa9b79.png">

**Comment by moritzschepp** [comment]
Ah I see ... this is because there had been the possibility to enter titles for media in a previous version. It seems our intern entered work titles in the medium title field. I removed them and deactivated the title field for media
