### ISSUE TITLE
The upload size is limited to 5 MB but just 0,5 are allowed and the error message is misleading

### ISSUE THREAD

**Issue by wuebbena** [coneda/kor#46]
<img width="741" alt="bildschirmfoto 2016-02-26 um 14 47 16" src="https://cloud.githubusercontent.com/assets/7914234/13353861/76c07688-dc97-11e5-8556-5d9477706b71.png">

**Comment by moritzschepp** [comment]
... well its just wrong ;) I'll fix that. The parsing for the configuration value isn't working, currently it just sets the value to "10kb".

**Comment by moritzschepp** [comment]
This is fixed.

**Comment by wuebbena** [comment]
It is. Thanks!
