### ISSUE TITLE
remove the session panel

### ISSUE THREAD

**Issue by wuebbena** [coneda/kor#47]
afaik the version 2.0 offers only the new way to link entities (btw: smart function but a little bit confusing under ui resp. usabilty aspects). anyway, why do we still need the section „session“?

**Comment by moritzschepp** [comment]
Yes I had thought about that as well: the session panel shows the current entity. I'm happy to drop it but we are still using the current entity on the clipboard and during multi file upload. should we drop it anyhow?

**Comment by wuebbena** [comment]
You're absolutely right. So if we drop the session we do need a replacement to keep the clipboard workable.

**Comment by moritzschepp** [comment]
Theoretically, we could still drop the session panel. There would then not be a way to see the current entity without actually navigating to the multi file upload or the clipboard. What do you think?

**Comment by wuebbena** [comment]
I think we should ask some of the end user in Frankfurt.

**Comment by wuebbena** [comment]
Yes, I should ask one or two. :-)

**Comment by moritzschepp** [comment]
Any news?

**Comment by wuebbena** [comment]
O.K., let's get rid of it!

**Comment by moritzschepp** [comment]
The milestone for this doesn't exist anymore, but the work is done. Please close if you have no objections.
