### ISSUE TITLE
align expert search behavior to simple search

### ISSUE THREAD

**Issue by bitno** [coneda/kor#48]
starting point: select expert search.
steps to reproduce: select an entity type -> additional fields for this selected type appear.
enhancement: as soon as a type is selected, display search results for that type. The same is already the case for the simple search. This would provide the user an immediate response to his selection, without going to the search button first. From there on the user can enter search terms and continue to narrow his search results.

**Comment by moritzschepp** [comment]
Its done.

**Comment by moritzschepp** [comment]
... @bitno can you close issues, actually?

**Comment by bitno** [comment]
many thanks @moritzschepp
