### ISSUE TITLE
new relationship editor: reduce amount of results for last visited

### ISSUE THREAD

**Issue by bitno** [coneda/kor#49]
starting point: open relationship editor on any given entity
steps to reproduce: click on "last created"
problem: currently 12 objects are shown, which causes unnecessary scrolling to create the new relationship. Would it make sense to reduce the objects to 9, meaning a 3x3 matrix? Or to allow the user to define the amount of objects or to allow the user to flip through several pages of these?
![bildschirmfoto 2016-02-26 um 17 13 50](https://cloud.githubusercontent.com/assets/15378927/13357781/58d577bc-dcac-11e5-953e-f03b15164777.png)

**Comment by moritzschepp** [comment]
Its done.
