### ISSUE TITLE
unique identifiers for collections, fields and generators

### ISSUE THREAD

**Issue by S-Peter** [coneda/kor#52]
* when updating a record, that has previously been imported via oaipmh, I am not able to retrieve a particular collection, field or generator, since they don't have uuids
* collection, field and generators only have a local id, i.e. the id in the database they came from. One could either create a new column in each of the tables in the harvesting database to store the local id from the provider database or a column for a uuid, in order to match these records between provider and harvester. The second solution seems more advantageous to me, since it would allow more effective retrieval of the records

**Comment by moritzschepp** [comment]
Good point. I can see how uuids make sense for fields. I'll add this!

Then I was just thinking about the generators and their purpose: They provide small additions to the representation of entities. Strictly speaking, they are not part of the the metadata, nor do they describe the schema. We could just exclude them entirely while harvesting. What do you think?

About the collections: Could we not ignore them as well? Even if it might be desirable to select only a few collections from a remote repository, I'd implement that using OAI-PMH "sets". A harvesting process would then always synchronize into one local collection. In this way, we wouldn't have to re-create collections.

**Comment by S-Peter** [comment]
I agree: I think it would be a good idea to treat collections as sets, that would be more genuinely oaipmh, and since the generators are - as I understand - used for representational purposes of the data, they do not strictly speaking belong to the data itself. 
In my current implementation I got around having uuids for fields in simply deleting and recreating all fields of a kind each time I make an update. But the problem persists that I can't select a certain field individually, which already when it comes to testing is a problem.

**Comment by moritzschepp** [comment]
I added a uuid to the fields
