### ISSUE TITLE
hierarchical semantics

### ISSUE THREAD

**Issue by moritzschepp** [coneda/kor#53]
@S-Peter, you pointed out that an inheritance model based on the CIDOC CRM would greatly enhance interoperability between installations and data modelling for project owners. For this to work, we need a hierarchy among kinds and relations with these specs:
- a kind can have 0, 1 or many parents
- a pair of kinds inherit available relations from their entire ancestry
- a relation can have 0, 1 or many parents ~~1 parents (@S-Peter, please verify)~~
- by default, a derived relation should allow the same entity types as its parent. The admin should be able to restrict this to derivatives of the parents entity types.
- multiple inheritance for relations should only be permitted if that doesn't create conflicts with permitted entity types

Obviously, there are more features to think about, but this is the essential part.

**Comment by moritzschepp** [comment]
@S-Peter, do you think it might make sense to limit relations in kor to allow just one entity type at each side to better approach the concept of domain and range?

**Comment by S-Peter** [comment]
there is indeed multiple inheritance for properties as well in CIDOC CRM: cf. Definition CIDOC CRM 5.0.4 (http://www.cidoc-crm.org/docs/cidoc_crm_version_5.0.4.pdf), page xxi
the properties with multiple inheritance are: P108, P99, P142, P111
the inheritance is only "semantical" though, since the domain and range class of these properties are always the same, i.e. P108 has the same domain class E12 and the same range class E24 as a subproperty of P92 and P31, so there is no conflict between several possible domain and range classes

**Comment by S-Peter** [comment]
I think with the new (multiple) inheritance mechanism, it won't be necessary any more to define several domain and range entity types for kor relations; to avoid modelization inconsistencies I would recommend to limit relations to just one entity type

**Comment by moritzschepp** [comment]
Alright, then I'll remove multiple endpoint types, see #94.

With multiple inheritance for relations, we could allow to inherit from several relations as long as that doesn't create any conflict in endpoint selection. In other words: if I select two or more relations as parents for a new relation, the parents must have the same endpoints (or the endpoints must be derivables of each other). @S-Peter, what do you think?

**Comment by S-Peter** [comment]
Perfect!

**Comment by moritzschepp** [comment]
@wuebbena, I tried to further use visjs to enhance the graph rendering when displaying the kind hierarchy. However, it doesn't handle the multi-inheritance very well (since - from the point of view of the data structure - a single kind ends up at several hierarchy levels). There is another option (d3.js) that allows for more flexibility but that is also a lot more work. I am working on that for quite a few hours now. The result might be nice to look at but there is actually no functionality added except perhaps a (better) overview. In addition the use case is relatively small.

I would suggest that we drop the whole graph idea altogether and revert to a list or grid view. What do you think?

**Comment by wuebbena** [comment]
> “The result might be nice to look at but there is actually no functionality added except perhaps a (better) overview.“ 

is the key sentence. So let us drop the subject and it's no longer an issue.

**Comment by moritzschepp** [comment]
@wuebbena, I feel that this needs further clarification. I'll try to summarize what we talked about in various sessions. First there are the use cases, where we see two:

A: Within any specific KOR installation, inheritance would allow separate projects to work with their respective vocabularies without giving up on reference model compliance.

B: When data (kinds, relations, entities and relationship) were to be transferred and copied from one installation to another, the same advantage as A applies.

We agreed that implementing inheritable functionality (possible endpoints for relations, fields and/or generators for kinds) creates more problems than it solves. Also, the use case is small because the manual work to create the same effect only has to be done once when integrating a semantically different dataset for the first time.

In the current `nested_kinds` branch, we have the functionality to declare kinds as "abstract", which removes them from the list of possible kinds when creating entities. To stay with an example: Given an existing kind "people" and a newly introduced kind "artists", which one would be abstract? Does this concept make sense at all? The same question would be valid for the search: Should it be possible to search for people only? If yes, how does the project working on "artists" search for their content?

**Comment by moritzschepp** [comment]
After a discussing it with @wuebbena, we decided that A is actually not feasible at the moment, due to workflow incompatibilities. We will therefore concentrate on B and expect a single installation to hold only a reference model and at most one additional vocabulary (the one of the research project at hand).

This also makes the concept of "abstract" kinds sufficient.
