### ISSUE TITLE
Relationship Editor not working on test environment

### ISSUE THREAD

**Issue by bitno** [coneda/kor#61]
Relationships added through the new inline relationship-edior are currently not being saved on the v2.0 testing environment.

starting point: url/blaze#/entities/157
steps to reproduce: add relation "hat geschaffen" chose any "werk" and press "save".
outcome: none, the new relation is not being added.

**Comment by moritzschepp** [comment]
Right, I had activated a security feature which broke this.

**Comment by bitno** [comment]
Perfect, seems to work now. I'll close the issue asap. Thank you @moritzschepp !
