### ISSUE TITLE
Relationship Editor not working on master

### ISSUE THREAD

**Issue by bitno** [coneda/kor#62]
The new inline relationship-edior is currently not being displayed properly on the v2.0 master.

starting point: conedakor0a and conedakor0b
steps to reproduce: add relation to any given entity
outcome: not editor is displayed, see screenshot
![bildschirmfoto 2016-03-31 um 14 12 04](https://cloud.githubusercontent.com/assets/15378927/14175456/59decfe6-f74b-11e5-9c3b-11274387369f.png)

**Comment by moritzschepp** [comment]
It seems like the page wasn't loaded correctly. Can you try again (I just tried and it works fine)? If this happens again, please open the browser inspector and post any messages you may find there.

**Comment by bitno** [comment]
Dear @moritzschepp, it seems the issue is still apparent even in the current master (2.0.0-pre). See attached screenshot from a few minutes ago.
<img width="800" alt="bildschirmfoto 2016-05-06 um 09 34 36" src="https://cloud.githubusercontent.com/assets/15378927/15067060/f2944e3a-136d-11e6-9576-2278808cbbe9.png">

**Comment by moritzschepp** [comment]
I can't reproduce the bug. I tried on "rechercheportal" but both chrome and firefox work fine. Perhaps your browser has some old assets cached? Try to refresh without cache: https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache and see if that helps

**Comment by bitno** [comment]
This did solve the problem and after having tried another dozen times, it showed up correctly each single time.
For Safari it was "Shift" and "Refresh".
This also seems to have sold ticket #65, as I was not able to reproduce the issue since the refresh.
