### ISSUE TITLE
Simple search not displaying search results

### ISSUE THREAD

**Issue by bitno** [coneda/kor#64]
User is on simple search and either selects an entity type or searches for a term. The number of hits is shown, but not the actual entities, they stay blank.
Screenshot is from an older master 2.0, but the upgrade to the current master didn't solve the issue. 
Can be reproduced here: http://rechercheportal.gta.arch.ethz.ch/component_search
![bildschirmfoto 2016-04-28 um 16 14 09](https://cloud.githubusercontent.com/assets/15378927/15066664/42d9e042-136b-11e6-839a-8c06621f2d86.png)
![bildschirmfoto 2016-04-28 um 16 15 08](https://cloud.githubusercontent.com/assets/15378927/15066666/4cf2cd8c-136b-11e6-90f6-22046deac484.png)
![bildschirmfoto 2016-04-28 um 16 16 18](https://cloud.githubusercontent.com/assets/15378927/15066671/530f8052-136b-11e6-9ac6-e33e24ba1ca9.png)

**Comment by moritzschepp** [comment]
This is an error returned by elasticsearch. The service seems to be online, otherwise you'd see connection failures. Sometimes, the index needs to be rebuilt like this:

`RAILS_ENV=production bundle exec bin/kor index-all`

Can you try and see if it helps?

**Comment by bitno** [comment]
Thank you @moritzschepp ! 
Worked like a charm, will add this to our documentation.

**Comment by moritzschepp** [comment]
I just added it to the readme and it will show with my next commit.
