### ISSUE TITLE
Administrative information not displayed properly for logged in users

### ISSUE THREAD

**Issue by bitno** [coneda/kor#65]
A logged in user is viewing any given entity. The display on the bottom of the page is not complete, meaning descriptions/titles of the fields shown are not displayed. See screenshot, which was taken from the current master (2.0.0-pre).
![bildschirmfoto 2016-05-06 um 09 50 09](https://cloud.githubusercontent.com/assets/15378927/15067416/65307980-1370-11e6-9614-3170650b8eaf.png)

**Comment by moritzschepp** [comment]
I can't reproduce this with my installation. Can you open the in-browser inspector and refresh the page so that console errors are visible and then take another screenshot?

**Comment by bitno** [comment]
I'll try to do so. It has to be noted, that this is not happening all the time, but at random. Mostly a refresh of the site is enough to achieve a correct display. But I will try to capture it.

**Comment by bitno** [comment]
![bildschirmfoto 2016-05-06 um 10 21 45](https://cloud.githubusercontent.com/assets/15378927/15067983/81fceedc-1374-11e6-9822-08ea35eeebdb.png)

What is of interest to you? No errors are being detected.

**Comment by bitno** [comment]
See ticket #62 
Thank you @moritzschepp
