### ISSUE TITLE
Mailer configuration has no effect

### ISSUE THREAD

**Issue by moritzschepp** [coneda/kor#67]
The defaults set on `config/kor.defaults.yml` don't work anymore and the hardcoded defaults seem to be used.

Workaround: Add `config.action_mailer.delivery_method = :sendmail` to `config/environments/production.rb`

**Comment by bitno** [comment]
Dear @moritzschepp, the issue has popped up again on the latest master. Your workaround does not work any longer and the settings on the UI look different too, server and port are missing. Can you please tell me, what to change, in order to have emails up and working again? Many thanks!

**Comment by moritzschepp** [comment]
So the `config/kor.defaults.yml` now contains default settings for production like this:

    production:
      mail:
        delivery_method: smtp
        smtp_settings:
          host: 127.0.0.1
          port: 25
          enable_starttls_auto: false

You can ether make your host receive emails on 127.0.0.1:25 via smtp. Or you can configure an override in `config/kor.yml` such as

     production:
      mail:
        delivery_method: sendmail

The settings are passed to action_mailer directly:
http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration

**Comment by anthon** [comment]
@bitno, I'm not sure this is the issue we're seeing. @moritzschepp, the gist from the error log:

>An SMTP From address is required to send a message. Set the message smtp_envelope_from, return_path, sender, or from address.
{"controller"=>"users", "action"=>"reset_password", "id"=>"22"}

It seems no default From is passed to ActionMailer.

**Comment by moritzschepp** [comment]
I just added a test and there seems to be no problem with the shipped version of kor.defaults.yml. Is the site operator's name and mail address set (according to the web ui)?

**Comment by bitno** [comment]
@moritzschepp, where would this data have to be set exactly?

**Comment by bitno** [comment]
@anthon have you tried setting the email to coneda@gta.arch.ethz.ch in the web ui? Maybe the admin@conedakor8.ethz.ch is not set up yet.

**Comment by anthon** [comment]
Ok, so ActionMailer uses Site Operator > Mail address, but disregards Email > Sender address.

**Comment by moritzschepp** [comment]
Well no, not really: ActionMailer receives the configuration for making contact with a mail server, setting defaults and encryption.

I think filling in (Administration -> General -> Site Operator) Name and Mail Address is all you should need. I will remove the "Mail" section entirely because it serves no purpose anymore.

**Comment by anthon** [comment]
Yes, that's what I meant: it works as soon as you fill in the Site Operator > Mail address. Tiptop.
