### ISSUE TITLE
JSON API: Allow for arrays in id params

### ISSUE THREAD

**Issue by anthon** [coneda/kor#71]
I'm adding this one too, because it's easier than email. :)

It would be brilliant to be able to pass multiple `id`s to queries in the params, when applicable. This used to be possible via the `/api/1.0/...` route, but I'm guessing this was a conedakor1 hack.

Something like this:
```
/directed_relationships.json?from_ids[]=<:id1>&from_ids[]=<:id2>...
/entities.json?kind_ids[]=<:id1>&kind_ids[]=<:id2>...
```
and perhaps even
```
/entities.json?ids[]=<:id1>&ids[]=<:id2>...
```

**Comment by anthon** [comment]
Or even better: proper lists, to keep the query string within length limits:
```
/entities.json?ids=<:id1>+<:id2>+<:id3>...
```

**Comment by moritzschepp** [comment]
Right, good idea. I'll get on that next week. I'm at the airport and boarding should start any minute.

**Comment by anthon** [comment]
Works perfectly for `/relationships.json`!

Now, `/entities.json?kind_id=1,2,3,4,...` would be absolutely super. :)

**Comment by anthon** [comment]
Could you re-open this one, @moritzschepp? Just so it isn't forgotten. Or is there a problem with enabling it for the other endpoints?

**Comment by moritzschepp** [comment]
... right!
