### ISSUE TITLE
JSON API: Populating Medium on single entity query

### ISSUE THREAD

**Issue by anthon** [coneda/kor#72]
As far as I can see, there's currently no way of getting an entity with included media. Neither `/show_full` nor `&media=true` seem to be working anymore.

Ideally, this would be solved by implementing #70 (so I'm hooking them up, here).

This would make sense, right? Media relationships are conceptually much closer than other relationships.

**Comment by moritzschepp** [comment]
There is no difference between a relationship between a medium entity (one where medium_id is set) and and a non-media entity (where medium_id is null or undefined) and any other relationship. Essentially this is the same request as #69, just with an additional filter on entity types.

**Comment by anthon** [comment]
>Essentially this is the same request as #69, just with an additional filter on entity types.

From a structural point of view, you're absolutely right, but in practice they're very different. The current setup (assuming the new array params) means there's a mandatory 3 requests + _n_ media requests per single entity displayed in a browser. The reason #69 is on ice is that its use case is too narrow, but I'm pretty sure most applications will want to show related media as close to the single entity as possible.

What about something like `/component_search`'s `images: [...]`? Only with all size URLs and including all mime types. Or would it make more sense to expand on `/component_search`?

**Comment by moritzschepp** [comment]
Yes, something like `/component_search`'s `images` could be done. But those are strictly limited to a maximum of 4 (unsorted) media entities. Is that enough? I guess with a bit of SQL sub query trickery, I could even compress that into a single query so that this is still possible for the 500 entities you are asking for in one of the commit comments.

**Comment by anthon** [comment]
The `per_page` limit is specific to querying multiple results (and the config option for max `per_page` is a super idea!), and this issue is related to querying one single entity.

What about if there was a `?show_full=true` or an '?include_media=true` or an `?include_relation=<:relation_name>,<:relation_name,...`? That in combination with a manually added sorting property to the media relationships (#73) could make waves!

**Comment by moritzschepp** [comment]
So how would you handle the pagination within the embedded entities? Let's say there is an entity with 1000 related images? In #69 I suggested to embed the first 10 (or whatever few) but you said that this wouldn't help much. We are having the same problem here, no?

If I understand you correctly, you are saying that this would work if you had a sorting mechanism (on the embedded entities)? Unfortunatelly, order within the graph is not easy (read fast) to solve at the moment.

There is no way to make this issue "depend" on #69 on github, is there? Or would you like to close this issue and reopen #69 as the more generic feature?

**Comment by anthon** [comment]
As I see it, #69, #70 and this issue are very similar, but have one big difference in terms of functionality: media relationships are more direct than other relationships. The likelihood of someone wanting to immediately get related media in an entity query is higher than any other elated entities. Like in the admin interface search, in the single entity view etc. In the admin interface the `component_search` has a very custom output (4 very low-res medium URLs, sorted how?), and in the single entity view it's all rendered on the server. But as soon as you want to use the JSON API to display anything, you very quickly get into XHR hell.

I'm not sure about all the other KOR instances running, but as far as I can see, the scenario where a single entity is related to 1000+ images is way more far-fetched than the need for displaying images close to an entity fetch – single (like here) or multiple (#70). If the amount of attached media is a concern, then I'd just cap it at (for example) 100 for a single entity query and 5 or even 1 for a multiple entities query (#70). In the latter case, it's only about getting a thumbnail for list display. If there's a way to say "get all entities according to condition blabla, and `include_relations=1,2,3`" and that would generate a list of entities with the first relationship of the specified relations included, that would be enough for most listing scenarios.

I'm not claiming to have the perfect solution, but do you see the problem/need?

**Comment by moritzschepp** [comment]
Absolutely! I also understand that there is a more frequent use case for including related media than for including related whatever. The point is not so much to see how likely a certain constellation within the graph is but rather if it is possible to create it: If you build a software with a way to do X, at some point, somebody will do X and at that moment, we are looking at request times of tens of seconds. We had that with an Installation in Frankfurt and users had to wait regularly for 30 seconds to show a single entity (blocking the server process for other work). This is why we capped the amount of returned results wherever there are results to return (applying pagination for the remaining data).

You just wrote that you could live with the cap, so we can make you happy, I believe :)

* we implement #69 allowing for choice of `media=(true|false)` and `relation_name=blablub`, capping the amount of embedded entities
* we include high res urls when media is returned (embedded or not).
* we implement that behavior for `/entities.json` and `/entities/1.json` with varying caps (good idea!).

That should cover #69, #70 and it would allow to keep #73 a separate feature which the others don't depend on. Sounds good?

**Comment by anthon** [comment]
You're a hero, @moritzschepp. Yes, that sounds all good (and I also understand completely the "if there's a way..." problem). Some thoughts:

- Would `relation_name=...` be enabling the inclusion of other relationships? Then that should be enough, right? Perhaps the name should be "include" or something. The `media=true|false` could be omitted, and you could simply call `/entities.json?include=has_attachment` and you'd get entities with a capped amount of included media relationships. That would mean bigger objects when including media entities, but it would be very generic.
- The inclusion could also be a list, like the id lists (#71): You could then also do `/entities.json?include=has_thumbnail,was_written_by,was_written_in`.
- All these caps should probably be config params, right?

**Comment by moritzschepp** [comment]
Right, however:

Unfortunately, the current backend requires results that are reliably media (or not) so I can't drop the `media=(true|false)` but we could make it a `kind_id=1,2,3` so that its more generic.

**Comment by anthon** [comment]
Ok, alles klar. Is `kind_id=1,2,3` is probably better than enabling inclusion by relation name, right? IDs are more elegant, but names are more readable. And I guess it's fair to expect front-end developers to know what IDs the relations have. What do you think?

**Comment by moritzschepp** [comment]
I think we need both: `kind_id` would describe the type of the related entity while `relation_name` would describe the type of relationship. Both can be mixed and matched arbitrarily.

**Comment by anthon** [comment]
Ah, but wait – `kind_id` is already reserved for the 1st order entity in an `/entities.json` request. Would make sense to synchronise the query var names for both `/entities.json` and `/entities/1.json`. So that would make it `to_kind_id=1,2,3`?

**Comment by moritzschepp** [comment]
I had to go with a different set of parameters and documented it within the README.

**Comment by anthon** [comment]
Yep, got it. Took me a few min to figure out that you need to specify `include=related`. :) But it works like a charm!
