### ISSUE TITLE
Admin: include media in 'create link' live search

### ISSUE THREAD

**Issue by anthon** [coneda/kor#77]
Right now the only way to create a relationship including an already existing Medium is to start from the Medium itself.
If `include_media=true` were added to the API call in the Entity > Links > Create Link > Search field, the relationship could be added in both directions.

**Comment by moritzschepp** [comment]
... only that there is no reasonable search terms applicable to media entities. Like in #78, the result would be a listing of all media entities and that is already available on the 'recently created' tab.

**Comment by anthon** [comment]
Ah, I see. Wasn't aware that `terms` only searches names. Thought it was similar to the `component_search`. The functionality would be a nice feature to add in the future sometime though, right?

**Comment by moritzschepp** [comment]
The question would be: in what fields would you actually search?

**Comment by anthon** [comment]
`type`, `description`, Additional Properties..?

**Comment by moritzschepp** [comment]
According to you, would it make more sense to attach a search to "new entries" to get the functionality or to enhance the simple/expert search?

**Comment by anthon** [comment]
See the reply in #78.

The functionality I meant, that would be really nice, is however the stuff above: To be able to relate already existing media to an entity from within the entity itself, and not from the media. Would be a lot faster workflow.

But really, this is non-crucial. Just an enhancement idea.
