### ISSUE TITLE
Admin: Searches to include type Medium

### ISSUE THREAD

**Issue by anthon** [coneda/kor#78]
Would make sense if Search > Entity Type would include Medium, right? I think that used to be the case, so perhaps there's a reason it's gone.

**Comment by moritzschepp** [comment]
The search a concept where you are actually using a search term to filter entities. Since there is no text to be searched within a medium entity, no search term could be applied. The result would then be a sheer listing of all media entities. This listing is already available under "new entries".

**Comment by anthon** [comment]
I'm moving this from #77:

>According to you, would it make more sense to attach a search to "new entries" to get the functionality or to enhance the simple/expert search?

I'd enhance the regular searches. Otherwise we'll end up with 3 different search interfaces.
And the simple search till uses component_search, right? So could that actually already search the text attributes of a Medium?
