### ISSUE TITLE
GetRecord response 403 Forbidden

### ISSUE THREAD

**Issue by S-Peter** [coneda/kor#8]
trying to access OAI-PMH interface with verb GetRecord triggers a 403 Forbidden response even though logged in

**Comment by moritzschepp** [comment]
I just used the following curl call and had no issues. Does that work for you as well?

    curl -v -H "api_key: <valid user key>" "http://localhost:3000/api/oai_pmh/entities.xml?verb=GetRecord&identifier=<valid entity identifier>"

**Comment by S-Peter** [comment]
Works perfectly. Thanks a lot!
