### ISSUE TITLE
configuration changes do not persist

### ISSUE THREAD

**Issue by moritzschepp** [coneda/kor#82]
... it seems that the default configuration is loaded after the processes has been running for a while.

**Comment by anthon** [comment]
Ah. that explains it. :)

@bitno – you might have to make that `max_included_results_per_result ` setting again, at some point.

@moritzschepp – is this a tricky one? And do you know what triggers the reset (not git pull, I assume)? We'll be presenting an instance tomorrow, and it would be great to know if I need to create a workaround.

**Comment by moritzschepp** [comment]
Well I don't know why its dropping the configuration yet. I assumed that it happens when one makes changes via the web interface but I just tested that and it works as expected. Do you remember what you did right before the config was lost?

**Comment by anthon** [comment]
Have no idea, and @bitno would have more into on exactly what was reset; `max_included_results_per_result ` was reset, but not `max_results_per_request ` (which is set to 100 by default, right?).

**Comment by moritzschepp** [comment]
So then we are dealing with a different issue here: In another installation, I had upgraded the app and then the config was reset to default values. Restarting the app did load the correct information again. I tend to think that the missing restart after the app was the problem.

In your case, did you experience config loss? `max_included_results_per_result` has a default of 4 and max_results_per_page has 500. Also see `config/kor.defaults.yml`.

**Comment by anthon** [comment]
Ah, yes, then I guess it could be that the complete configure was reset on pull. @bitno?

**Comment by moritzschepp** [comment]
Or by the first saving of new config values after the cleanup of the config yml. In any case, that would have been fixed with a restart of the app.

**Comment by moritzschepp** [comment]
This should be fixed now
