### ISSUE TITLE
API: Include media relationship params

### ISSUE THREAD

**Issue by anthon** [coneda/kor#87]
Related to #73: As far as I can see, additional properties on media relationships aren't output via API calls. Or am I missing something?

**Comment by moritzschepp** [comment]
Can you post an exact call to the API?

**Comment by anthon** [comment]
Oups, just realised I never replied to this. Did you catch it?

**Comment by moritzschepp** [comment]
I think so, there is the `GET /entities/1/relationships.json` which now includes the properties. Let me know if you are missing them somewhere else.

**Comment by anthon** [comment]
Yep, perfect.
