### ISSUE TITLE
JSON API: CORS headers missing

### ISSUE THREAD

**Issue by anthon** [coneda/kor#91]
I'm guessing something changed in the last push?

**Comment by moritzschepp** [comment]
There is now a configuration option that allows to send CORS headers via the app itself, see https://github.com/coneda/kor#widgets. In the past, we just did that within the apache configuration (which should be unaffected). I'll send you an email and we can investigate the exact issue.

**Comment by anthon** [comment]
Ok, super. I'll inform @bitno about it (he's doing everything server on the ETH instances).

**Comment by moritzschepp** [comment]
Excellent, thanks!
