### ISSUE TITLE
Widget settings to have same functionality as before (pre-widget time)

### ISSUE THREAD

**Issue by bitno** [coneda/kor#92]
Dear @moritzschepp , 
Where and how can one change and edit the widget settings, in order to restore the same functionality of the api, as before the widget functionality? 
Many thanks for helping out and lots of greetings,
Leo

**Comment by moritzschepp** [comment]
@bitno Are you referring to the CORS header settings? Have a look at https://github.com/coneda/kor#widgets and refer to https://github.com/coneda/kor/blob/master/config/kor.defaults.yml for how to use the `allowed_origins` setting.

**Comment by bitno** [comment]
I worked with the defaults, but without success. Let me try it again later today and I will report/attach the files, should I again not succeed.

**Comment by moritzschepp** [comment]
You need to specify which hosts are allowed to use the API via Javascript. If a page https://great-app.examle.com is to make requests to kor, you'll have to put that in the configuration: allowed_origins: ['https://great-app.example.com']. The default will not work.

**Comment by moritzschepp** [comment]
@bitno could you resolve the problem?

**Comment by bitno** [comment]
Dear @moritzschepp, I'm awaiting the response by Anthon, will get back at you asap. Many thanks in the meantime.

**Comment by bitno** [comment]
Dear @moritzschepp, worked fine, the application is up and running. Do I need to change this setting after each deployment or is there a way how to save this particular setting? Many thanks

**Comment by moritzschepp** [comment]
... the setting is part of the config file that is not part of the git repo. So when deploying via git, that is taken care of and if you deploy via deploy.sh or deploy/app.sh then the script will create symlinks to the config file in the `shared` dir which also persists the change.

**Comment by bitno** [comment]
Many many thanks! Good stuff
