### ISSUE TITLE
clear logo in the top left corner

### ISSUE THREAD

**Issue by bitno** [coneda/kor#93]
Dear @moritzschepp ,
Could you please provide a different format or a higher resolution logo, so that I can replace the current one in the top left corner?
Many thanks and lots of greetings,
Leo

**Comment by moritzschepp** [comment]
... so you'd like a larger version of the current ConedaKOR logo?

**Comment by moritzschepp** [comment]
So you'd like a larger version of the logo currently in use?

**Comment by bitno** [comment]
Correct or an eps file. Whatever is more convenient for you. Many thanks

**Comment by wuebbena** [comment]
Dear @bitno ,
I hope this one will fit: https://cloud.coneda.net/index.php/s/GEmynk35Py9Naoc
C u and a lot of greetings!
Thorsten

**Comment by bitno** [comment]
Dear @wuebbena, lots of thanks, that should work just fine.
