### ISSUE TITLE
how to reset/change admin password?

### ISSUE THREAD

**Issue by bitno** [coneda/kor#97]
Dear @moritzschepp, how can I change an admin password, if I don't know the current one? I have root access to the server however.
Many thanks and lots of greetings,
Leo

**Comment by moritzschepp** [comment]
... that can be done with the command line utility. Have a look at
https://github.com/coneda/kor#command-line-tool

If you run the help command, it will show you all the tasks it can perform. Make sure you run it with `RAILS_ENV=production` if that applies.

**Comment by bitno** [comment]
Many thanks @moritzschepp, will give it a try later today. Much appreciated!
